;;; Generated by tools/c2ffi-gen.ss from c2ffi output of ffi/bindings.h.
;;; Do not edit; run `make bindings` to regenerate.

(library (chezterm ffi)
  (export FT_Bitmap_Size_ FT_CharMapRec_ FT_Generic_ FT_BBox_
   FT_Glyph_Metrics_ FT_Vector_ FT_Bitmap_ FT_Outline_
   FT_GlyphSlotRec_ FT_Size_Metrics_ FT_SizeRec_ FT_MemoryRec_
   FT_StreamDesc_ FT_StreamRec_ FT_ListNodeRec_ FT_ListRec_
   FT_FaceRec_ FT_Matrix_ wl_message wl_interface wl_array
   wl_cursor_image wl_cursor pollfd winsize timespec itimerspec
   wl_argument malloc calloc free memcpy memmove memset strlen
   c-getenv setenv unsetenv setlocale wcwidth __errno_location
   strerror c-read c-write close pipe2 fcntl poll ioctl dup2
   mmap munmap ftruncate memfd_create fork setsid forkpty
   execvp _exit waitpid kill getpid chdir readlink
   timerfd_create timerfd_settime sigemptyset sigprocmask
   signal wl_display_connect wl_display_disconnect
   wl_display_get_fd wl_display_dispatch
   wl_display_dispatch_pending wl_display_flush
   wl_display_roundtrip wl_display_prepare_read
   wl_display_read_events wl_display_cancel_read
   wl_display_get_error wl_proxy_marshal_array_flags
   wl_proxy_add_dispatcher wl_proxy_get_id wl_proxy_get_version
   wl_proxy_destroy wl_proxy_get_class wl_cursor_theme_load
   wl_cursor_theme_destroy wl_cursor_theme_get_cursor
   wl_cursor_image_get_buffer xkb_context_new xkb_context_unref
   xkb_keymap_new_from_string xkb_keymap_unref
   xkb_keymap_key_repeats xkb_keymap_mod_get_index
   xkb_state_new xkb_state_unref xkb_state_update_mask
   xkb_state_key_get_one_sym xkb_state_key_get_utf32
   xkb_state_mod_index_is_active xkb_keysym_to_utf32
   xkb_keysym_to_lower xkb_keysym_from_name xkb_keysym_get_name
   xkb_compose_table_new_from_locale xkb_compose_table_unref
   xkb_compose_state_new xkb_compose_state_unref
   xkb_compose_state_feed xkb_compose_state_reset
   xkb_compose_state_get_status xkb_compose_state_get_one_sym
   xkb_compose_state_get_utf8 FT_Init_FreeType FT_Done_FreeType
   FT_New_Face FT_Done_Face FT_Set_Pixel_Sizes FT_Select_Size
   FT_Get_Char_Index FT_Load_Glyph FT_Render_Glyph
   FT_Library_SetLcdFilter FT_Set_Transform
   FT_GlyphSlot_Embolden FT_GlyphSlot_Oblique
   FcInitLoadConfigAndFonts FcConfigDestroy FcConfigSubstitute
   FcDefaultSubstitute FcFontMatch FcNameParse FcPatternCreate
   FcPatternDestroy FcPatternDuplicate FcPatternAddString
   FcPatternAddInteger FcPatternAddDouble FcPatternAddBool
   FcPatternAddCharSet FcPatternDel FcPatternGetString
   FcPatternGetInteger FcPatternGetDouble FcPatternGetBool
   FcCharSetCreate FcCharSetAddChar FcCharSetDestroy
   FcCharSetHasChar FcPatternGetCharSet XKB_KEYSYM_NO_FLAGS
   XKB_KEYSYM_CASE_INSENSITIVE XKB_CONTEXT_NO_FLAGS
   XKB_KEYMAP_COMPILE_NO_FLAGS XKB_KEYMAP_FORMAT_TEXT_V1
   XKB_STATE_MODS_DEPRESSED XKB_STATE_MODS_LATCHED
   XKB_STATE_MODS_LOCKED XKB_STATE_MODS_EFFECTIVE
   XKB_STATE_LAYOUT_DEPRESSED XKB_STATE_LAYOUT_LATCHED
   XKB_STATE_LAYOUT_LOCKED XKB_STATE_LAYOUT_EFFECTIVE
   XKB_STATE_LEDS XKB_STATE_MATCH_ANY XKB_STATE_MATCH_ALL
   XKB_STATE_MATCH_NON_EXCLUSIVE XKB_COMPOSE_COMPILE_NO_FLAGS
   XKB_COMPOSE_FORMAT_TEXT_V1 XKB_COMPOSE_STATE_NO_FLAGS
   XKB_COMPOSE_NOTHING XKB_COMPOSE_COMPOSING
   XKB_COMPOSE_COMPOSED XKB_COMPOSE_CANCELLED
   XKB_COMPOSE_FEED_IGNORED XKB_COMPOSE_FEED_ACCEPTED
   FT_PIXEL_MODE_NONE FT_PIXEL_MODE_MONO FT_PIXEL_MODE_GRAY
   FT_PIXEL_MODE_GRAY2 FT_PIXEL_MODE_GRAY4 FT_PIXEL_MODE_LCD
   FT_PIXEL_MODE_LCD_V FT_PIXEL_MODE_BGRA FT_PIXEL_MODE_MAX
   FT_ENCODING_NONE FT_RENDER_MODE_NORMAL FT_RENDER_MODE_LIGHT
   FT_RENDER_MODE_MONO FT_RENDER_MODE_LCD FT_RENDER_MODE_LCD_V
   FT_RENDER_MODE_SDF FT_RENDER_MODE_MAX FT_LCD_FILTER_NONE
   FT_LCD_FILTER_DEFAULT FT_LCD_FILTER_LIGHT
   FT_LCD_FILTER_LEGACY1 FT_LCD_FILTER_LEGACY FT_LCD_FILTER_MAX
   FcResultMatch FcResultNoMatch FcResultTypeMismatch
   FcResultNoId FcResultOutOfMemory FcMatchPattern FcMatchFont
   FcMatchScan FcMatchKindEnd FcMatchKindBegin CLOCK_MONOTONIC
   EAGAIN EINTR EIO ENOENT EPIPE FC_ANTIALIAS FC_CHARSET
   FC_COLOR FC_DPI FC_FAMILY FC_FILE FC_HINTING FC_HINT_STYLE
   FC_INDEX FC_MONO FC_PIXEL_SIZE FC_RGBA FC_RGBA_BGR
   FC_RGBA_NONE FC_RGBA_RGB FC_RGBA_UNKNOWN FC_SCALABLE FC_SIZE
   FC_SLANT FC_SLANT_ITALIC FC_SLANT_ROMAN FC_SPACING FC_STYLE
   FC_WEIGHT FC_WEIGHT_BOLD FC_WEIGHT_REGULAR FD_CLOEXEC
   FT_FACE_FLAG_COLOR FT_FACE_FLAG_FIXED_SIZES
   FT_FACE_FLAG_SCALABLE FT_LOAD_COLOR FT_LOAD_DEFAULT
   FT_LOAD_FORCE_AUTOHINT FT_LOAD_NO_BITMAP FT_LOAD_NO_HINTING
   FT_LOAD_RENDER FT_LOAD_TARGET_LCD FT_LOAD_TARGET_LIGHT
   FT_LOAD_TARGET_MONO FT_LOAD_TARGET_NORMAL F_GETFL F_SETFD
   F_SETFL FcFalse FcTrue LC_ALL LC_CTYPE MAP_SHARED
   MFD_ALLOW_SEALING MFD_CLOEXEC O_CLOEXEC O_NONBLOCK POLLERR
   POLLHUP POLLIN POLLNVAL POLLOUT PROT_READ PROT_WRITE SIGCHLD
   SIGHUP SIGINT SIGPIPE SIGTERM SIG_SETMASK TFD_CLOEXEC
   TFD_NONBLOCK TIOCGPGRP TIOCSWINSZ WL_MARSHAL_FLAG_DESTROY
   WNOHANG)
  (import (chezscheme))
  (define shared-objects-loaded
    (begin
      (load-shared-object "libc.so.6")
      (load-shared-object "libwayland-client.so.0")
      (load-shared-object "libwayland-cursor.so.0")
      (load-shared-object "libxkbcommon.so.0")
      (load-shared-object "libfreetype.so.6")
      (load-shared-object "libfontconfig.so.1")
      #t))
  (define-ftype (FT_Bitmap_Size_
                  (struct
                    [height short]
                    [width short]
                    [size long]
                    [x_ppem long]
                    [y_ppem long]))
    (FT_CharMapRec_
      (struct
        [face (* FT_FaceRec_)]
        [encoding int]
        [platform_id unsigned-short]
        [encoding_id unsigned-short]))
    (FT_Generic_ (struct [data void*] [finalizer uptr]))
    (FT_BBox_
      (struct [xMin long] [yMin long] [xMax long] [yMax long]))
    (FT_Glyph_Metrics_
      (struct
        [width long]
        [height long]
        [horiBearingX long]
        [horiBearingY long]
        [horiAdvance long]
        [vertBearingX long]
        [vertBearingY long]
        [vertAdvance long]))
    (FT_Vector_ (struct [x long] [y long]))
    (FT_Bitmap_
      (struct
        [rows unsigned-int]
        [width unsigned-int]
        [pitch int]
        [buffer void*]
        [num_grays unsigned-short]
        [pixel_mode unsigned-8]
        [palette_mode unsigned-8]
        [palette void*]))
    (FT_Outline_
      (struct
        [n_contours short]
        [n_points short]
        [points (* FT_Vector_)]
        [tags void*]
        [contours void*]
        [flags int]))
    (FT_GlyphSlotRec_
      (struct
        [library void*]
        [face (* FT_FaceRec_)]
        [next (* FT_GlyphSlotRec_)]
        [glyph_index unsigned-int]
        [generic FT_Generic_]
        [metrics FT_Glyph_Metrics_]
        [linearHoriAdvance long]
        [linearVertAdvance long]
        [advance FT_Vector_]
        [format int]
        [bitmap FT_Bitmap_]
        [bitmap_left int]
        [bitmap_top int]
        [outline FT_Outline_]
        [num_subglyphs unsigned-int]
        [subglyphs void*]
        [control_data void*]
        [control_len long]
        [lsb_delta long]
        [rsb_delta long]
        [other void*]
        [internal void*]))
    (FT_Size_Metrics_
      (struct
        [x_ppem unsigned-short]
        [y_ppem unsigned-short]
        [x_scale long]
        [y_scale long]
        [ascender long]
        [descender long]
        [height long]
        [max_advance long]))
    (FT_SizeRec_
      (struct
        [face (* FT_FaceRec_)]
        [generic FT_Generic_]
        [metrics FT_Size_Metrics_]
        [internal void*]))
    (FT_MemoryRec_
      (struct
        [user void*]
        [alloc uptr]
        [free uptr]
        [realloc uptr]))
    (FT_StreamDesc_ (union [value long] [pointer void*]))
    (FT_StreamRec_
      (struct
        [base void*]
        [size unsigned-long]
        [pos unsigned-long]
        [descriptor FT_StreamDesc_]
        [pathname FT_StreamDesc_]
        [read uptr]
        [close uptr]
        [memory (* FT_MemoryRec_)]
        [cursor void*]
        [limit void*]))
    (FT_ListNodeRec_
      (struct
        [prev (* FT_ListNodeRec_)]
        [next (* FT_ListNodeRec_)]
        [data void*]))
    (FT_ListRec_
      (struct
        [head (* FT_ListNodeRec_)]
        [tail (* FT_ListNodeRec_)]))
    (FT_FaceRec_
      (struct
        [num_faces long]
        [face_index long]
        [face_flags long]
        [style_flags long]
        [num_glyphs long]
        [family_name void*]
        [style_name void*]
        [num_fixed_sizes int]
        [available_sizes (* FT_Bitmap_Size_)]
        [num_charmaps int]
        [charmaps void*]
        [generic FT_Generic_]
        [bbox FT_BBox_]
        [units_per_EM unsigned-short]
        [ascender short]
        [descender short]
        [height short]
        [max_advance_width short]
        [max_advance_height short]
        [underline_position short]
        [underline_thickness short]
        [glyph (* FT_GlyphSlotRec_)]
        [size (* FT_SizeRec_)]
        [charmap (* FT_CharMapRec_)]
        [driver void*]
        [memory (* FT_MemoryRec_)]
        [stream (* FT_StreamRec_)]
        [sizes_list FT_ListRec_]
        [autohint FT_Generic_]
        [extensions void*]
        [internal void*]))
    (FT_Matrix_
      (struct [xx long] [xy long] [yx long] [yy long]))
    (wl_message
      (struct [name void*] [signature void*] [types void*]))
    (wl_interface
      (struct
        [name void*]
        [version int]
        [method_count int]
        [methods (* wl_message)]
        [event_count int]
        [events (* wl_message)]))
    (wl_array
      (struct
        [size unsigned-long]
        [alloc unsigned-long]
        [data void*]))
    (wl_cursor_image
      (struct
        [width unsigned-int]
        [height unsigned-int]
        [hotspot_x unsigned-int]
        [hotspot_y unsigned-int]
        [delay unsigned-int]))
    (wl_cursor
      (struct
        [image_count unsigned-int]
        [images void*]
        [name void*]))
    (pollfd (struct [fd int] [events short] [revents short]))
    (winsize
      (struct
        [ws_row unsigned-short]
        [ws_col unsigned-short]
        [ws_xpixel unsigned-short]
        [ws_ypixel unsigned-short]))
    (timespec (struct [tv_sec long] [tv_nsec long]))
    (itimerspec
      (struct [it_interval timespec] [it_value timespec]))
    (wl_argument
      (union
        [i int]
        [u unsigned-int]
        [f int]
        [s void*]
        [o void*]
        [n unsigned-int]
        [a (* wl_array)]
        [h int])))
  (define malloc
    (foreign-procedure "malloc" (unsigned-long) uptr))
  (define calloc
    (foreign-procedure "calloc"
      (unsigned-long unsigned-long)
      uptr))
  (define free (foreign-procedure "free" (uptr) void))
  (define memcpy
    (foreign-procedure "memcpy" (uptr uptr unsigned-long) uptr))
  (define memmove
    (foreign-procedure "memmove"
      (uptr uptr unsigned-long)
      uptr))
  (define memset
    (foreign-procedure "memset" (uptr int unsigned-long) uptr))
  (define strlen
    (foreign-procedure "strlen" (uptr) unsigned-long))
  (define c-getenv (foreign-procedure "getenv" (utf-8) uptr))
  (define setenv
    (foreign-procedure "setenv" (utf-8 utf-8 int) int))
  (define unsetenv (foreign-procedure "unsetenv" (utf-8) int))
  (define setlocale
    (foreign-procedure "setlocale" (int utf-8) uptr))
  (define wcwidth (foreign-procedure "wcwidth" (int) int))
  (define __errno_location
    (foreign-procedure "__errno_location" () uptr))
  (define strerror (foreign-procedure "strerror" (int) uptr))
  (define c-read
    (foreign-procedure "read" (int u8* unsigned-long) long))
  (define c-write
    (foreign-procedure "write" (int u8* unsigned-long) long))
  (define close (foreign-procedure "close" (int) int))
  (define pipe2 (foreign-procedure "pipe2" (uptr int) int))
  (define fcntl (foreign-procedure "fcntl" (int int int) int))
  (define poll
    (foreign-procedure "poll" (uptr unsigned-long int) int))
  (define ioctl
    (foreign-procedure "ioctl" (int unsigned-long uptr) int))
  (define dup2 (foreign-procedure "dup2" (int int) int))
  (define mmap
    (foreign-procedure "mmap"
      (uptr unsigned-long int int int long)
      uptr))
  (define munmap
    (foreign-procedure "munmap" (uptr unsigned-long) int))
  (define ftruncate
    (foreign-procedure "ftruncate" (int long) int))
  (define memfd_create
    (foreign-procedure "memfd_create" (utf-8 unsigned-int) int))
  (define fork (foreign-procedure "fork" () int))
  (define setsid (foreign-procedure "setsid" () int))
  (define forkpty
    (foreign-procedure "forkpty" (uptr uptr uptr uptr) int))
  (define execvp (foreign-procedure "execvp" (uptr uptr) int))
  (define _exit (foreign-procedure "_exit" (int) void))
  (define waitpid
    (foreign-procedure "waitpid" (int uptr int) int))
  (define kill (foreign-procedure "kill" (int int) int))
  (define getpid (foreign-procedure "getpid" () int))
  (define chdir (foreign-procedure "chdir" (uptr) int))
  (define readlink
    (foreign-procedure "readlink"
      (utf-8 uptr unsigned-long)
      long))
  (define timerfd_create
    (foreign-procedure "timerfd_create" (int int) int))
  (define timerfd_settime
    (foreign-procedure "timerfd_settime"
      (int int uptr uptr)
      int))
  (define sigemptyset
    (foreign-procedure "sigemptyset" (uptr) int))
  (define sigprocmask
    (foreign-procedure "sigprocmask" (int uptr uptr) int))
  (define signal (foreign-procedure "signal" (int uptr) uptr))
  (define wl_display_connect
    (foreign-procedure "wl_display_connect" (utf-8) uptr))
  (define wl_display_disconnect
    (foreign-procedure "wl_display_disconnect" (uptr) void))
  (define wl_display_get_fd
    (foreign-procedure "wl_display_get_fd" (uptr) int))
  (define wl_display_dispatch
    (foreign-procedure "wl_display_dispatch" (uptr) int))
  (define wl_display_dispatch_pending
    (foreign-procedure "wl_display_dispatch_pending"
      (uptr)
      int))
  (define wl_display_flush
    (foreign-procedure "wl_display_flush" (uptr) int))
  (define wl_display_roundtrip
    (foreign-procedure "wl_display_roundtrip" (uptr) int))
  (define wl_display_prepare_read
    (foreign-procedure "wl_display_prepare_read" (uptr) int))
  (define wl_display_read_events
    (foreign-procedure "wl_display_read_events" (uptr) int))
  (define wl_display_cancel_read
    (foreign-procedure "wl_display_cancel_read" (uptr) void))
  (define wl_display_get_error
    (foreign-procedure "wl_display_get_error" (uptr) int))
  (define wl_proxy_marshal_array_flags
    (foreign-procedure "wl_proxy_marshal_array_flags"
      (uptr unsigned-int uptr unsigned-int unsigned-int uptr)
      uptr))
  (define wl_proxy_add_dispatcher
    (foreign-procedure "wl_proxy_add_dispatcher"
      (uptr uptr uptr uptr)
      int))
  (define wl_proxy_get_id
    (foreign-procedure "wl_proxy_get_id" (uptr) unsigned-int))
  (define wl_proxy_get_version
    (foreign-procedure "wl_proxy_get_version"
      (uptr)
      unsigned-int))
  (define wl_proxy_destroy
    (foreign-procedure "wl_proxy_destroy" (uptr) void))
  (define wl_proxy_get_class
    (foreign-procedure "wl_proxy_get_class" (uptr) uptr))
  (define wl_cursor_theme_load
    (foreign-procedure "wl_cursor_theme_load"
      (utf-8 int uptr)
      uptr))
  (define wl_cursor_theme_destroy
    (foreign-procedure "wl_cursor_theme_destroy" (uptr) void))
  (define wl_cursor_theme_get_cursor
    (foreign-procedure "wl_cursor_theme_get_cursor"
      (uptr utf-8)
      uptr))
  (define wl_cursor_image_get_buffer
    (foreign-procedure "wl_cursor_image_get_buffer"
      (uptr)
      uptr))
  (define xkb_context_new
    (foreign-procedure "xkb_context_new" (int) uptr))
  (define xkb_context_unref
    (foreign-procedure "xkb_context_unref" (uptr) void))
  (define xkb_keymap_new_from_string
    (foreign-procedure "xkb_keymap_new_from_string"
      (uptr uptr int int)
      uptr))
  (define xkb_keymap_unref
    (foreign-procedure "xkb_keymap_unref" (uptr) void))
  (define xkb_keymap_key_repeats
    (foreign-procedure "xkb_keymap_key_repeats"
      (uptr unsigned-int)
      int))
  (define xkb_keymap_mod_get_index
    (foreign-procedure "xkb_keymap_mod_get_index"
      (uptr utf-8)
      unsigned-int))
  (define xkb_state_new
    (foreign-procedure "xkb_state_new" (uptr) uptr))
  (define xkb_state_unref
    (foreign-procedure "xkb_state_unref" (uptr) void))
  (define xkb_state_update_mask
    (foreign-procedure "xkb_state_update_mask"
      (uptr
       unsigned-int
       unsigned-int
       unsigned-int
       unsigned-int
       unsigned-int
       unsigned-int)
      int))
  (define xkb_state_key_get_one_sym
    (foreign-procedure "xkb_state_key_get_one_sym"
      (uptr unsigned-int)
      unsigned-int))
  (define xkb_state_key_get_utf32
    (foreign-procedure "xkb_state_key_get_utf32"
      (uptr unsigned-int)
      unsigned-int))
  (define xkb_state_mod_index_is_active
    (foreign-procedure "xkb_state_mod_index_is_active"
      (uptr unsigned-int int)
      int))
  (define xkb_keysym_to_utf32
    (foreign-procedure "xkb_keysym_to_utf32"
      (unsigned-int)
      unsigned-int))
  (define xkb_keysym_to_lower
    (foreign-procedure "xkb_keysym_to_lower"
      (unsigned-int)
      unsigned-int))
  (define xkb_keysym_from_name
    (foreign-procedure "xkb_keysym_from_name"
      (utf-8 int)
      unsigned-int))
  (define xkb_keysym_get_name
    (foreign-procedure "xkb_keysym_get_name"
      (unsigned-int utf-8 unsigned-long)
      int))
  (define xkb_compose_table_new_from_locale
    (foreign-procedure "xkb_compose_table_new_from_locale"
      (uptr utf-8 int)
      uptr))
  (define xkb_compose_table_unref
    (foreign-procedure "xkb_compose_table_unref" (uptr) void))
  (define xkb_compose_state_new
    (foreign-procedure "xkb_compose_state_new" (uptr int) uptr))
  (define xkb_compose_state_unref
    (foreign-procedure "xkb_compose_state_unref" (uptr) void))
  (define xkb_compose_state_feed
    (foreign-procedure "xkb_compose_state_feed"
      (uptr unsigned-int)
      int))
  (define xkb_compose_state_reset
    (foreign-procedure "xkb_compose_state_reset" (uptr) void))
  (define xkb_compose_state_get_status
    (foreign-procedure "xkb_compose_state_get_status"
      (uptr)
      int))
  (define xkb_compose_state_get_one_sym
    (foreign-procedure "xkb_compose_state_get_one_sym"
      (uptr)
      unsigned-int))
  (define xkb_compose_state_get_utf8
    (foreign-procedure "xkb_compose_state_get_utf8"
      (uptr uptr unsigned-long)
      int))
  (define FT_Init_FreeType
    (foreign-procedure "FT_Init_FreeType" (uptr) int))
  (define FT_Done_FreeType
    (foreign-procedure "FT_Done_FreeType" (uptr) int))
  (define FT_New_Face
    (foreign-procedure "FT_New_Face"
      (uptr utf-8 long uptr)
      int))
  (define FT_Done_Face
    (foreign-procedure "FT_Done_Face" (uptr) int))
  (define FT_Set_Pixel_Sizes
    (foreign-procedure "FT_Set_Pixel_Sizes"
      (uptr unsigned-int unsigned-int)
      int))
  (define FT_Select_Size
    (foreign-procedure "FT_Select_Size" (uptr int) int))
  (define FT_Get_Char_Index
    (foreign-procedure "FT_Get_Char_Index"
      (uptr unsigned-long)
      unsigned-int))
  (define FT_Load_Glyph
    (foreign-procedure "FT_Load_Glyph"
      (uptr unsigned-int int)
      int))
  (define FT_Render_Glyph
    (foreign-procedure "FT_Render_Glyph" (uptr int) int))
  (define FT_Library_SetLcdFilter
    (foreign-procedure "FT_Library_SetLcdFilter"
      (uptr int)
      int))
  (define FT_Set_Transform
    (foreign-procedure "FT_Set_Transform"
      (uptr uptr uptr)
      void))
  (define FT_GlyphSlot_Embolden
    (foreign-procedure "FT_GlyphSlot_Embolden" (uptr) void))
  (define FT_GlyphSlot_Oblique
    (foreign-procedure "FT_GlyphSlot_Oblique" (uptr) void))
  (define FcInitLoadConfigAndFonts
    (foreign-procedure "FcInitLoadConfigAndFonts" () uptr))
  (define FcConfigDestroy
    (foreign-procedure "FcConfigDestroy" (uptr) void))
  (define FcConfigSubstitute
    (foreign-procedure "FcConfigSubstitute"
      (uptr uptr int)
      int))
  (define FcDefaultSubstitute
    (foreign-procedure "FcDefaultSubstitute" (uptr) void))
  (define FcFontMatch
    (foreign-procedure "FcFontMatch" (uptr uptr uptr) uptr))
  (define FcNameParse
    (foreign-procedure "FcNameParse" (uptr) uptr))
  (define FcPatternCreate
    (foreign-procedure "FcPatternCreate" () uptr))
  (define FcPatternDestroy
    (foreign-procedure "FcPatternDestroy" (uptr) void))
  (define FcPatternDuplicate
    (foreign-procedure "FcPatternDuplicate" (uptr) uptr))
  (define FcPatternAddString
    (foreign-procedure "FcPatternAddString"
      (uptr utf-8 uptr)
      int))
  (define FcPatternAddInteger
    (foreign-procedure "FcPatternAddInteger"
      (uptr utf-8 int)
      int))
  (define FcPatternAddDouble
    (foreign-procedure "FcPatternAddDouble"
      (uptr utf-8 double)
      int))
  (define FcPatternAddBool
    (foreign-procedure "FcPatternAddBool" (uptr utf-8 int) int))
  (define FcPatternAddCharSet
    (foreign-procedure "FcPatternAddCharSet"
      (uptr utf-8 uptr)
      int))
  (define FcPatternDel
    (foreign-procedure "FcPatternDel" (uptr utf-8) int))
  (define FcPatternGetString
    (foreign-procedure "FcPatternGetString"
      (uptr utf-8 int uptr)
      int))
  (define FcPatternGetInteger
    (foreign-procedure "FcPatternGetInteger"
      (uptr utf-8 int uptr)
      int))
  (define FcPatternGetDouble
    (foreign-procedure "FcPatternGetDouble"
      (uptr utf-8 int uptr)
      int))
  (define FcPatternGetBool
    (foreign-procedure "FcPatternGetBool"
      (uptr utf-8 int uptr)
      int))
  (define FcCharSetCreate
    (foreign-procedure "FcCharSetCreate" () uptr))
  (define FcCharSetAddChar
    (foreign-procedure "FcCharSetAddChar"
      (uptr unsigned-int)
      int))
  (define FcCharSetDestroy
    (foreign-procedure "FcCharSetDestroy" (uptr) void))
  (define FcCharSetHasChar
    (foreign-procedure "FcCharSetHasChar"
      (uptr unsigned-int)
      int))
  (define FcPatternGetCharSet
    (foreign-procedure "FcPatternGetCharSet"
      (uptr utf-8 int uptr)
      int))
  (define XKB_KEYSYM_NO_FLAGS 0)
  (define XKB_KEYSYM_CASE_INSENSITIVE 1)
  (define XKB_CONTEXT_NO_FLAGS 0)
  (define XKB_KEYMAP_COMPILE_NO_FLAGS 0)
  (define XKB_KEYMAP_FORMAT_TEXT_V1 1)
  (define XKB_STATE_MODS_DEPRESSED 1)
  (define XKB_STATE_MODS_LATCHED 2)
  (define XKB_STATE_MODS_LOCKED 4)
  (define XKB_STATE_MODS_EFFECTIVE 8)
  (define XKB_STATE_LAYOUT_DEPRESSED 16)
  (define XKB_STATE_LAYOUT_LATCHED 32)
  (define XKB_STATE_LAYOUT_LOCKED 64)
  (define XKB_STATE_LAYOUT_EFFECTIVE 128)
  (define XKB_STATE_LEDS 256)
  (define XKB_STATE_MATCH_ANY 1)
  (define XKB_STATE_MATCH_ALL 2)
  (define XKB_STATE_MATCH_NON_EXCLUSIVE 65536)
  (define XKB_COMPOSE_COMPILE_NO_FLAGS 0)
  (define XKB_COMPOSE_FORMAT_TEXT_V1 1)
  (define XKB_COMPOSE_STATE_NO_FLAGS 0)
  (define XKB_COMPOSE_NOTHING 0)
  (define XKB_COMPOSE_COMPOSING 1)
  (define XKB_COMPOSE_COMPOSED 2)
  (define XKB_COMPOSE_CANCELLED 3)
  (define XKB_COMPOSE_FEED_IGNORED 0)
  (define XKB_COMPOSE_FEED_ACCEPTED 1)
  (define FT_PIXEL_MODE_NONE 0)
  (define FT_PIXEL_MODE_MONO 1)
  (define FT_PIXEL_MODE_GRAY 2)
  (define FT_PIXEL_MODE_GRAY2 3)
  (define FT_PIXEL_MODE_GRAY4 4)
  (define FT_PIXEL_MODE_LCD 5)
  (define FT_PIXEL_MODE_LCD_V 6)
  (define FT_PIXEL_MODE_BGRA 7)
  (define FT_PIXEL_MODE_MAX 8)
  (define FT_ENCODING_NONE 0)
  (define FT_RENDER_MODE_NORMAL 0)
  (define FT_RENDER_MODE_LIGHT 1)
  (define FT_RENDER_MODE_MONO 2)
  (define FT_RENDER_MODE_LCD 3)
  (define FT_RENDER_MODE_LCD_V 4)
  (define FT_RENDER_MODE_SDF 5)
  (define FT_RENDER_MODE_MAX 6)
  (define FT_LCD_FILTER_NONE 0)
  (define FT_LCD_FILTER_DEFAULT 1)
  (define FT_LCD_FILTER_LIGHT 2)
  (define FT_LCD_FILTER_LEGACY1 3)
  (define FT_LCD_FILTER_LEGACY 16)
  (define FT_LCD_FILTER_MAX 17)
  (define FcResultMatch 0)
  (define FcResultNoMatch 1)
  (define FcResultTypeMismatch 2)
  (define FcResultNoId 3)
  (define FcResultOutOfMemory 4)
  (define FcMatchPattern 0)
  (define FcMatchFont 1)
  (define FcMatchScan 2)
  (define FcMatchKindEnd 3)
  (define FcMatchKindBegin 0)
  (define CLOCK_MONOTONIC 1)
  (define EAGAIN 11)
  (define EINTR 4)
  (define EIO 5)
  (define ENOENT 2)
  (define EPIPE 32)
  (define FC_ANTIALIAS "antialias")
  (define FC_CHARSET "charset")
  (define FC_COLOR "color")
  (define FC_DPI "dpi")
  (define FC_FAMILY "family")
  (define FC_FILE "file")
  (define FC_HINTING "hinting")
  (define FC_HINT_STYLE "hintstyle")
  (define FC_INDEX "index")
  (define FC_MONO 100)
  (define FC_PIXEL_SIZE "pixelsize")
  (define FC_RGBA "rgba")
  (define FC_RGBA_BGR 2)
  (define FC_RGBA_NONE 5)
  (define FC_RGBA_RGB 1)
  (define FC_RGBA_UNKNOWN 0)
  (define FC_SCALABLE "scalable")
  (define FC_SIZE "size")
  (define FC_SLANT "slant")
  (define FC_SLANT_ITALIC 100)
  (define FC_SLANT_ROMAN 0)
  (define FC_SPACING "spacing")
  (define FC_STYLE "style")
  (define FC_WEIGHT "weight")
  (define FC_WEIGHT_BOLD 200)
  (define FC_WEIGHT_REGULAR 80)
  (define FD_CLOEXEC 1)
  (define FT_FACE_FLAG_COLOR 16384)
  (define FT_FACE_FLAG_FIXED_SIZES 2)
  (define FT_FACE_FLAG_SCALABLE 1)
  (define FT_LOAD_COLOR 1048576)
  (define FT_LOAD_DEFAULT 0)
  (define FT_LOAD_FORCE_AUTOHINT 32)
  (define FT_LOAD_NO_BITMAP 8)
  (define FT_LOAD_NO_HINTING 2)
  (define FT_LOAD_RENDER 4)
  (define FT_LOAD_TARGET_LCD 196608)
  (define FT_LOAD_TARGET_LIGHT 65536)
  (define FT_LOAD_TARGET_MONO 131072)
  (define FT_LOAD_TARGET_NORMAL 0)
  (define F_GETFL 3)
  (define F_SETFD 2)
  (define F_SETFL 4)
  (define FcFalse 0)
  (define FcTrue 1)
  (define LC_ALL 6)
  (define LC_CTYPE 0)
  (define MAP_SHARED 1)
  (define MFD_ALLOW_SEALING 2)
  (define MFD_CLOEXEC 1)
  (define O_CLOEXEC 524288)
  (define O_NONBLOCK 2048)
  (define POLLERR 8)
  (define POLLHUP 16)
  (define POLLIN 1)
  (define POLLNVAL 32)
  (define POLLOUT 4)
  (define PROT_READ 1)
  (define PROT_WRITE 2)
  (define SIGCHLD 17)
  (define SIGHUP 1)
  (define SIGINT 2)
  (define SIGPIPE 13)
  (define SIGTERM 15)
  (define SIG_SETMASK 2)
  (define TFD_CLOEXEC 524288)
  (define TFD_NONBLOCK 2048)
  (define TIOCGPGRP 21519)
  (define TIOCSWINSZ 21524)
  (define WL_MARSHAL_FLAG_DESTROY 1)
  (define WNOHANG 1))
