;;; Generated by tools/wl-scanner.ss from:
;;;   protocols/wayland.xml
;;;   protocols/xdg-shell.xml
;;;   protocols/xdg-decoration-unstable-v1.xml
;;;   protocols/primary-selection-unstable-v1.xml
;;;   protocols/cursor-shape-v1.xml
;;; Do not edit; run `make protocols` to regenerate.

(library (chezterm protocols)
  (export wl_display wl_registry wl_callback wl_compositor
   wl_shm_pool wl_shm wl_buffer wl_data_offer wl_data_source
   wl_data_device wl_data_device_manager wl_shell
   wl_shell_surface wl_surface wl_seat wl_pointer wl_keyboard
   wl_touch wl_output wl_region wl_subcompositor wl_subsurface
   xdg_wm_base xdg_positioner xdg_surface xdg_toplevel
   xdg_popup zxdg_decoration_manager_v1
   zxdg_toplevel_decoration_v1
   zwp_primary_selection_device_manager_v1
   zwp_primary_selection_device_v1
   zwp_primary_selection_offer_v1
   zwp_primary_selection_source_v1 wp_cursor_shape_manager_v1
   wp_cursor_shape_device_v1 WL_DISPLAY_ERROR_INVALID_OBJECT
   WL_DISPLAY_ERROR_INVALID_METHOD WL_DISPLAY_ERROR_NO_MEMORY
   WL_DISPLAY_ERROR_IMPLEMENTATION WL_SHM_ERROR_INVALID_FORMAT
   WL_SHM_ERROR_INVALID_STRIDE WL_SHM_ERROR_INVALID_FD
   WL_SHM_FORMAT_ARGB8888 WL_SHM_FORMAT_XRGB8888
   WL_SHM_FORMAT_C8 WL_SHM_FORMAT_RGB332 WL_SHM_FORMAT_BGR233
   WL_SHM_FORMAT_XRGB4444 WL_SHM_FORMAT_XBGR4444
   WL_SHM_FORMAT_RGBX4444 WL_SHM_FORMAT_BGRX4444
   WL_SHM_FORMAT_ARGB4444 WL_SHM_FORMAT_ABGR4444
   WL_SHM_FORMAT_RGBA4444 WL_SHM_FORMAT_BGRA4444
   WL_SHM_FORMAT_XRGB1555 WL_SHM_FORMAT_XBGR1555
   WL_SHM_FORMAT_RGBX5551 WL_SHM_FORMAT_BGRX5551
   WL_SHM_FORMAT_ARGB1555 WL_SHM_FORMAT_ABGR1555
   WL_SHM_FORMAT_RGBA5551 WL_SHM_FORMAT_BGRA5551
   WL_SHM_FORMAT_RGB565 WL_SHM_FORMAT_BGR565
   WL_SHM_FORMAT_RGB888 WL_SHM_FORMAT_BGR888
   WL_SHM_FORMAT_XBGR8888 WL_SHM_FORMAT_RGBX8888
   WL_SHM_FORMAT_BGRX8888 WL_SHM_FORMAT_ABGR8888
   WL_SHM_FORMAT_RGBA8888 WL_SHM_FORMAT_BGRA8888
   WL_SHM_FORMAT_XRGB2101010 WL_SHM_FORMAT_XBGR2101010
   WL_SHM_FORMAT_RGBX1010102 WL_SHM_FORMAT_BGRX1010102
   WL_SHM_FORMAT_ARGB2101010 WL_SHM_FORMAT_ABGR2101010
   WL_SHM_FORMAT_RGBA1010102 WL_SHM_FORMAT_BGRA1010102
   WL_SHM_FORMAT_YUYV WL_SHM_FORMAT_YVYU WL_SHM_FORMAT_UYVY
   WL_SHM_FORMAT_VYUY WL_SHM_FORMAT_AYUV WL_SHM_FORMAT_NV12
   WL_SHM_FORMAT_NV21 WL_SHM_FORMAT_NV16 WL_SHM_FORMAT_NV61
   WL_SHM_FORMAT_YUV410 WL_SHM_FORMAT_YVU410
   WL_SHM_FORMAT_YUV411 WL_SHM_FORMAT_YVU411
   WL_SHM_FORMAT_YUV420 WL_SHM_FORMAT_YVU420
   WL_SHM_FORMAT_YUV422 WL_SHM_FORMAT_YVU422
   WL_SHM_FORMAT_YUV444 WL_SHM_FORMAT_YVU444 WL_SHM_FORMAT_R8
   WL_SHM_FORMAT_R16 WL_SHM_FORMAT_RG88 WL_SHM_FORMAT_GR88
   WL_SHM_FORMAT_RG1616 WL_SHM_FORMAT_GR1616
   WL_SHM_FORMAT_XRGB16161616F WL_SHM_FORMAT_XBGR16161616F
   WL_SHM_FORMAT_ARGB16161616F WL_SHM_FORMAT_ABGR16161616F
   WL_SHM_FORMAT_XYUV8888 WL_SHM_FORMAT_VUY888
   WL_SHM_FORMAT_VUY101010 WL_SHM_FORMAT_Y210
   WL_SHM_FORMAT_Y212 WL_SHM_FORMAT_Y216 WL_SHM_FORMAT_Y410
   WL_SHM_FORMAT_Y412 WL_SHM_FORMAT_Y416
   WL_SHM_FORMAT_XVYU2101010 WL_SHM_FORMAT_XVYU12_16161616
   WL_SHM_FORMAT_XVYU16161616 WL_SHM_FORMAT_Y0L0
   WL_SHM_FORMAT_X0L0 WL_SHM_FORMAT_Y0L2 WL_SHM_FORMAT_X0L2
   WL_SHM_FORMAT_YUV420_8BIT WL_SHM_FORMAT_YUV420_10BIT
   WL_SHM_FORMAT_XRGB8888_A8 WL_SHM_FORMAT_XBGR8888_A8
   WL_SHM_FORMAT_RGBX8888_A8 WL_SHM_FORMAT_BGRX8888_A8
   WL_SHM_FORMAT_RGB888_A8 WL_SHM_FORMAT_BGR888_A8
   WL_SHM_FORMAT_RGB565_A8 WL_SHM_FORMAT_BGR565_A8
   WL_SHM_FORMAT_NV24 WL_SHM_FORMAT_NV42 WL_SHM_FORMAT_P210
   WL_SHM_FORMAT_P010 WL_SHM_FORMAT_P012 WL_SHM_FORMAT_P016
   WL_SHM_FORMAT_AXBXGXRX106106106106 WL_SHM_FORMAT_NV15
   WL_SHM_FORMAT_Q410 WL_SHM_FORMAT_Q401
   WL_SHM_FORMAT_XRGB16161616 WL_SHM_FORMAT_XBGR16161616
   WL_SHM_FORMAT_ARGB16161616 WL_SHM_FORMAT_ABGR16161616
   WL_DATA_OFFER_ERROR_INVALID_FINISH
   WL_DATA_OFFER_ERROR_INVALID_ACTION_MASK
   WL_DATA_OFFER_ERROR_INVALID_ACTION
   WL_DATA_OFFER_ERROR_INVALID_OFFER
   WL_DATA_SOURCE_ERROR_INVALID_ACTION_MASK
   WL_DATA_SOURCE_ERROR_INVALID_SOURCE
   WL_DATA_DEVICE_ERROR_ROLE
   WL_DATA_DEVICE_MANAGER_DND_ACTION_NONE
   WL_DATA_DEVICE_MANAGER_DND_ACTION_COPY
   WL_DATA_DEVICE_MANAGER_DND_ACTION_MOVE
   WL_DATA_DEVICE_MANAGER_DND_ACTION_ASK WL_SHELL_ERROR_ROLE
   WL_SHELL_SURFACE_RESIZE_NONE WL_SHELL_SURFACE_RESIZE_TOP
   WL_SHELL_SURFACE_RESIZE_BOTTOM WL_SHELL_SURFACE_RESIZE_LEFT
   WL_SHELL_SURFACE_RESIZE_TOP_LEFT
   WL_SHELL_SURFACE_RESIZE_BOTTOM_LEFT
   WL_SHELL_SURFACE_RESIZE_RIGHT
   WL_SHELL_SURFACE_RESIZE_TOP_RIGHT
   WL_SHELL_SURFACE_RESIZE_BOTTOM_RIGHT
   WL_SHELL_SURFACE_TRANSIENT_INACTIVE
   WL_SHELL_SURFACE_FULLSCREEN_METHOD_DEFAULT
   WL_SHELL_SURFACE_FULLSCREEN_METHOD_SCALE
   WL_SHELL_SURFACE_FULLSCREEN_METHOD_DRIVER
   WL_SHELL_SURFACE_FULLSCREEN_METHOD_FILL
   WL_SURFACE_ERROR_INVALID_SCALE
   WL_SURFACE_ERROR_INVALID_TRANSFORM
   WL_SURFACE_ERROR_INVALID_SIZE
   WL_SURFACE_ERROR_INVALID_OFFSET
   WL_SURFACE_ERROR_DEFUNCT_ROLE_OBJECT
   WL_SEAT_CAPABILITY_POINTER WL_SEAT_CAPABILITY_KEYBOARD
   WL_SEAT_CAPABILITY_TOUCH WL_SEAT_ERROR_MISSING_CAPABILITY
   WL_POINTER_ERROR_ROLE WL_POINTER_BUTTON_STATE_RELEASED
   WL_POINTER_BUTTON_STATE_PRESSED
   WL_POINTER_AXIS_VERTICAL_SCROLL
   WL_POINTER_AXIS_HORIZONTAL_SCROLL
   WL_POINTER_AXIS_SOURCE_WHEEL WL_POINTER_AXIS_SOURCE_FINGER
   WL_POINTER_AXIS_SOURCE_CONTINUOUS
   WL_POINTER_AXIS_SOURCE_WHEEL_TILT
   WL_POINTER_AXIS_RELATIVE_DIRECTION_IDENTICAL
   WL_POINTER_AXIS_RELATIVE_DIRECTION_INVERTED
   WL_KEYBOARD_KEYMAP_FORMAT_NO_KEYMAP
   WL_KEYBOARD_KEYMAP_FORMAT_XKB_V1
   WL_KEYBOARD_KEY_STATE_RELEASED WL_KEYBOARD_KEY_STATE_PRESSED
   WL_OUTPUT_SUBPIXEL_UNKNOWN WL_OUTPUT_SUBPIXEL_NONE
   WL_OUTPUT_SUBPIXEL_HORIZONTAL_RGB
   WL_OUTPUT_SUBPIXEL_HORIZONTAL_BGR
   WL_OUTPUT_SUBPIXEL_VERTICAL_RGB
   WL_OUTPUT_SUBPIXEL_VERTICAL_BGR WL_OUTPUT_TRANSFORM_NORMAL
   WL_OUTPUT_TRANSFORM_90 WL_OUTPUT_TRANSFORM_180
   WL_OUTPUT_TRANSFORM_270 WL_OUTPUT_TRANSFORM_FLIPPED
   WL_OUTPUT_TRANSFORM_FLIPPED_90
   WL_OUTPUT_TRANSFORM_FLIPPED_180
   WL_OUTPUT_TRANSFORM_FLIPPED_270 WL_OUTPUT_MODE_CURRENT
   WL_OUTPUT_MODE_PREFERRED WL_SUBCOMPOSITOR_ERROR_BAD_SURFACE
   WL_SUBCOMPOSITOR_ERROR_BAD_PARENT
   WL_SUBSURFACE_ERROR_BAD_SURFACE XDG_WM_BASE_ERROR_ROLE
   XDG_WM_BASE_ERROR_DEFUNCT_SURFACES
   XDG_WM_BASE_ERROR_NOT_THE_TOPMOST_POPUP
   XDG_WM_BASE_ERROR_INVALID_POPUP_PARENT
   XDG_WM_BASE_ERROR_INVALID_SURFACE_STATE
   XDG_WM_BASE_ERROR_INVALID_POSITIONER
   XDG_WM_BASE_ERROR_UNRESPONSIVE
   XDG_POSITIONER_ERROR_INVALID_INPUT
   XDG_POSITIONER_ANCHOR_NONE XDG_POSITIONER_ANCHOR_TOP
   XDG_POSITIONER_ANCHOR_BOTTOM XDG_POSITIONER_ANCHOR_LEFT
   XDG_POSITIONER_ANCHOR_RIGHT XDG_POSITIONER_ANCHOR_TOP_LEFT
   XDG_POSITIONER_ANCHOR_BOTTOM_LEFT
   XDG_POSITIONER_ANCHOR_TOP_RIGHT
   XDG_POSITIONER_ANCHOR_BOTTOM_RIGHT
   XDG_POSITIONER_GRAVITY_NONE XDG_POSITIONER_GRAVITY_TOP
   XDG_POSITIONER_GRAVITY_BOTTOM XDG_POSITIONER_GRAVITY_LEFT
   XDG_POSITIONER_GRAVITY_RIGHT XDG_POSITIONER_GRAVITY_TOP_LEFT
   XDG_POSITIONER_GRAVITY_BOTTOM_LEFT
   XDG_POSITIONER_GRAVITY_TOP_RIGHT
   XDG_POSITIONER_GRAVITY_BOTTOM_RIGHT
   XDG_POSITIONER_CONSTRAINT_ADJUSTMENT_NONE
   XDG_POSITIONER_CONSTRAINT_ADJUSTMENT_SLIDE_X
   XDG_POSITIONER_CONSTRAINT_ADJUSTMENT_SLIDE_Y
   XDG_POSITIONER_CONSTRAINT_ADJUSTMENT_FLIP_X
   XDG_POSITIONER_CONSTRAINT_ADJUSTMENT_FLIP_Y
   XDG_POSITIONER_CONSTRAINT_ADJUSTMENT_RESIZE_X
   XDG_POSITIONER_CONSTRAINT_ADJUSTMENT_RESIZE_Y
   XDG_SURFACE_ERROR_NOT_CONSTRUCTED
   XDG_SURFACE_ERROR_ALREADY_CONSTRUCTED
   XDG_SURFACE_ERROR_UNCONFIGURED_BUFFER
   XDG_SURFACE_ERROR_INVALID_SERIAL
   XDG_SURFACE_ERROR_INVALID_SIZE
   XDG_SURFACE_ERROR_DEFUNCT_ROLE_OBJECT
   XDG_TOPLEVEL_ERROR_INVALID_RESIZE_EDGE
   XDG_TOPLEVEL_ERROR_INVALID_PARENT
   XDG_TOPLEVEL_ERROR_INVALID_SIZE
   XDG_TOPLEVEL_RESIZE_EDGE_NONE XDG_TOPLEVEL_RESIZE_EDGE_TOP
   XDG_TOPLEVEL_RESIZE_EDGE_BOTTOM
   XDG_TOPLEVEL_RESIZE_EDGE_LEFT
   XDG_TOPLEVEL_RESIZE_EDGE_TOP_LEFT
   XDG_TOPLEVEL_RESIZE_EDGE_BOTTOM_LEFT
   XDG_TOPLEVEL_RESIZE_EDGE_RIGHT
   XDG_TOPLEVEL_RESIZE_EDGE_TOP_RIGHT
   XDG_TOPLEVEL_RESIZE_EDGE_BOTTOM_RIGHT
   XDG_TOPLEVEL_STATE_MAXIMIZED XDG_TOPLEVEL_STATE_FULLSCREEN
   XDG_TOPLEVEL_STATE_RESIZING XDG_TOPLEVEL_STATE_ACTIVATED
   XDG_TOPLEVEL_STATE_TILED_LEFT XDG_TOPLEVEL_STATE_TILED_RIGHT
   XDG_TOPLEVEL_STATE_TILED_TOP XDG_TOPLEVEL_STATE_TILED_BOTTOM
   XDG_TOPLEVEL_STATE_SUSPENDED
   XDG_TOPLEVEL_STATE_CONSTRAINED_LEFT
   XDG_TOPLEVEL_STATE_CONSTRAINED_RIGHT
   XDG_TOPLEVEL_STATE_CONSTRAINED_TOP
   XDG_TOPLEVEL_STATE_CONSTRAINED_BOTTOM
   XDG_TOPLEVEL_WM_CAPABILITIES_WINDOW_MENU
   XDG_TOPLEVEL_WM_CAPABILITIES_MAXIMIZE
   XDG_TOPLEVEL_WM_CAPABILITIES_FULLSCREEN
   XDG_TOPLEVEL_WM_CAPABILITIES_MINIMIZE
   XDG_POPUP_ERROR_INVALID_GRAB
   ZXDG_TOPLEVEL_DECORATION_V1_ERROR_UNCONFIGURED_BUFFER
   ZXDG_TOPLEVEL_DECORATION_V1_ERROR_ALREADY_CONSTRUCTED
   ZXDG_TOPLEVEL_DECORATION_V1_ERROR_ORPHANED
   ZXDG_TOPLEVEL_DECORATION_V1_ERROR_INVALID_MODE
   ZXDG_TOPLEVEL_DECORATION_V1_MODE_CLIENT_SIDE
   ZXDG_TOPLEVEL_DECORATION_V1_MODE_SERVER_SIDE
   WP_CURSOR_SHAPE_DEVICE_V1_SHAPE_DEFAULT
   WP_CURSOR_SHAPE_DEVICE_V1_SHAPE_CONTEXT_MENU
   WP_CURSOR_SHAPE_DEVICE_V1_SHAPE_HELP
   WP_CURSOR_SHAPE_DEVICE_V1_SHAPE_POINTER
   WP_CURSOR_SHAPE_DEVICE_V1_SHAPE_PROGRESS
   WP_CURSOR_SHAPE_DEVICE_V1_SHAPE_WAIT
   WP_CURSOR_SHAPE_DEVICE_V1_SHAPE_CELL
   WP_CURSOR_SHAPE_DEVICE_V1_SHAPE_CROSSHAIR
   WP_CURSOR_SHAPE_DEVICE_V1_SHAPE_TEXT
   WP_CURSOR_SHAPE_DEVICE_V1_SHAPE_VERTICAL_TEXT
   WP_CURSOR_SHAPE_DEVICE_V1_SHAPE_ALIAS
   WP_CURSOR_SHAPE_DEVICE_V1_SHAPE_COPY
   WP_CURSOR_SHAPE_DEVICE_V1_SHAPE_MOVE
   WP_CURSOR_SHAPE_DEVICE_V1_SHAPE_NO_DROP
   WP_CURSOR_SHAPE_DEVICE_V1_SHAPE_NOT_ALLOWED
   WP_CURSOR_SHAPE_DEVICE_V1_SHAPE_GRAB
   WP_CURSOR_SHAPE_DEVICE_V1_SHAPE_GRABBING
   WP_CURSOR_SHAPE_DEVICE_V1_SHAPE_E_RESIZE
   WP_CURSOR_SHAPE_DEVICE_V1_SHAPE_N_RESIZE
   WP_CURSOR_SHAPE_DEVICE_V1_SHAPE_NE_RESIZE
   WP_CURSOR_SHAPE_DEVICE_V1_SHAPE_NW_RESIZE
   WP_CURSOR_SHAPE_DEVICE_V1_SHAPE_S_RESIZE
   WP_CURSOR_SHAPE_DEVICE_V1_SHAPE_SE_RESIZE
   WP_CURSOR_SHAPE_DEVICE_V1_SHAPE_SW_RESIZE
   WP_CURSOR_SHAPE_DEVICE_V1_SHAPE_W_RESIZE
   WP_CURSOR_SHAPE_DEVICE_V1_SHAPE_EW_RESIZE
   WP_CURSOR_SHAPE_DEVICE_V1_SHAPE_NS_RESIZE
   WP_CURSOR_SHAPE_DEVICE_V1_SHAPE_NESW_RESIZE
   WP_CURSOR_SHAPE_DEVICE_V1_SHAPE_NWSE_RESIZE
   WP_CURSOR_SHAPE_DEVICE_V1_SHAPE_COL_RESIZE
   WP_CURSOR_SHAPE_DEVICE_V1_SHAPE_ROW_RESIZE
   WP_CURSOR_SHAPE_DEVICE_V1_SHAPE_ALL_SCROLL
   WP_CURSOR_SHAPE_DEVICE_V1_SHAPE_ZOOM_IN
   WP_CURSOR_SHAPE_DEVICE_V1_SHAPE_ZOOM_OUT
   WP_CURSOR_SHAPE_DEVICE_V1_SHAPE_DND_ASK
   WP_CURSOR_SHAPE_DEVICE_V1_SHAPE_ALL_RESIZE
   WP_CURSOR_SHAPE_DEVICE_V1_ERROR_INVALID_SHAPE
   wl_display_sync wl_display_get_registry wl_registry_bind
   wl_registry_destroy wl_callback_destroy
   wl_compositor_create_surface wl_compositor_create_region
   wl_compositor_destroy wl_shm_pool_create_buffer
   wl_shm_pool_destroy wl_shm_pool_resize wl_shm_create_pool
   wl_shm_destroy wl_buffer_destroy wl_data_offer_accept
   wl_data_offer_receive wl_data_offer_destroy
   wl_data_offer_finish wl_data_offer_set_actions
   wl_data_source_offer wl_data_source_destroy
   wl_data_source_set_actions wl_data_device_start_drag
   wl_data_device_set_selection wl_data_device_release
   wl_data_device_destroy
   wl_data_device_manager_create_data_source
   wl_data_device_manager_get_data_device
   wl_data_device_manager_destroy wl_shell_get_shell_surface
   wl_shell_destroy wl_shell_surface_pong wl_shell_surface_move
   wl_shell_surface_resize wl_shell_surface_set_toplevel
   wl_shell_surface_set_transient
   wl_shell_surface_set_fullscreen wl_shell_surface_set_popup
   wl_shell_surface_set_maximized wl_shell_surface_set_title
   wl_shell_surface_set_class wl_shell_surface_destroy
   wl_surface_destroy wl_surface_attach wl_surface_damage
   wl_surface_frame wl_surface_set_opaque_region
   wl_surface_set_input_region wl_surface_commit
   wl_surface_set_buffer_transform wl_surface_set_buffer_scale
   wl_surface_damage_buffer wl_surface_offset
   wl_seat_get_pointer wl_seat_get_keyboard wl_seat_get_touch
   wl_seat_release wl_seat_destroy wl_pointer_set_cursor
   wl_pointer_release wl_pointer_destroy wl_keyboard_release
   wl_keyboard_destroy wl_touch_release wl_touch_destroy
   wl_output_release wl_output_destroy wl_region_destroy
   wl_region_add wl_region_subtract wl_subcompositor_destroy
   wl_subcompositor_get_subsurface wl_subsurface_destroy
   wl_subsurface_set_position wl_subsurface_place_above
   wl_subsurface_place_below wl_subsurface_set_sync
   wl_subsurface_set_desync xdg_wm_base_destroy
   xdg_wm_base_create_positioner xdg_wm_base_get_xdg_surface
   xdg_wm_base_pong xdg_positioner_destroy
   xdg_positioner_set_size xdg_positioner_set_anchor_rect
   xdg_positioner_set_anchor xdg_positioner_set_gravity
   xdg_positioner_set_constraint_adjustment
   xdg_positioner_set_offset xdg_positioner_set_reactive
   xdg_positioner_set_parent_size
   xdg_positioner_set_parent_configure xdg_surface_destroy
   xdg_surface_get_toplevel xdg_surface_get_popup
   xdg_surface_set_window_geometry xdg_surface_ack_configure
   xdg_toplevel_destroy xdg_toplevel_set_parent
   xdg_toplevel_set_title xdg_toplevel_set_app_id
   xdg_toplevel_show_window_menu xdg_toplevel_move
   xdg_toplevel_resize xdg_toplevel_set_max_size
   xdg_toplevel_set_min_size xdg_toplevel_set_maximized
   xdg_toplevel_unset_maximized xdg_toplevel_set_fullscreen
   xdg_toplevel_unset_fullscreen xdg_toplevel_set_minimized
   xdg_popup_destroy xdg_popup_grab xdg_popup_reposition
   zxdg_decoration_manager_v1_destroy
   zxdg_decoration_manager_v1_get_toplevel_decoration
   zxdg_toplevel_decoration_v1_destroy
   zxdg_toplevel_decoration_v1_set_mode
   zxdg_toplevel_decoration_v1_unset_mode
   zwp_primary_selection_device_manager_v1_create_source
   zwp_primary_selection_device_manager_v1_get_device
   zwp_primary_selection_device_manager_v1_destroy
   zwp_primary_selection_device_v1_set_selection
   zwp_primary_selection_device_v1_destroy
   zwp_primary_selection_offer_v1_receive
   zwp_primary_selection_offer_v1_destroy
   zwp_primary_selection_source_v1_offer
   zwp_primary_selection_source_v1_destroy
   wp_cursor_shape_manager_v1_destroy
   wp_cursor_shape_manager_v1_get_pointer
   wp_cursor_shape_manager_v1_get_tablet_tool_v2
   wp_cursor_shape_device_v1_destroy
   wp_cursor_shape_device_v1_set_shape)
  (import (chezscheme) (chezterm wayland))
  (define wl_display (make-wl-interface "wl_display" 1))
  (define wl_registry (make-wl-interface "wl_registry" 1))
  (define wl_callback (make-wl-interface "wl_callback" 1))
  (define wl_compositor (make-wl-interface "wl_compositor" 6))
  (define wl_shm_pool (make-wl-interface "wl_shm_pool" 1))
  (define wl_shm (make-wl-interface "wl_shm" 1))
  (define wl_buffer (make-wl-interface "wl_buffer" 1))
  (define wl_data_offer (make-wl-interface "wl_data_offer" 3))
  (define wl_data_source
    (make-wl-interface "wl_data_source" 3))
  (define wl_data_device
    (make-wl-interface "wl_data_device" 3))
  (define wl_data_device_manager
    (make-wl-interface "wl_data_device_manager" 3))
  (define wl_shell (make-wl-interface "wl_shell" 1))
  (define wl_shell_surface
    (make-wl-interface "wl_shell_surface" 1))
  (define wl_surface (make-wl-interface "wl_surface" 6))
  (define wl_seat (make-wl-interface "wl_seat" 9))
  (define wl_pointer (make-wl-interface "wl_pointer" 9))
  (define wl_keyboard (make-wl-interface "wl_keyboard" 9))
  (define wl_touch (make-wl-interface "wl_touch" 9))
  (define wl_output (make-wl-interface "wl_output" 4))
  (define wl_region (make-wl-interface "wl_region" 1))
  (define wl_subcompositor
    (make-wl-interface "wl_subcompositor" 1))
  (define wl_subsurface (make-wl-interface "wl_subsurface" 1))
  (define xdg_wm_base (make-wl-interface "xdg_wm_base" 7))
  (define xdg_positioner
    (make-wl-interface "xdg_positioner" 7))
  (define xdg_surface (make-wl-interface "xdg_surface" 7))
  (define xdg_toplevel (make-wl-interface "xdg_toplevel" 7))
  (define xdg_popup (make-wl-interface "xdg_popup" 7))
  (define zxdg_decoration_manager_v1
    (make-wl-interface "zxdg_decoration_manager_v1" 1))
  (define zxdg_toplevel_decoration_v1
    (make-wl-interface "zxdg_toplevel_decoration_v1" 1))
  (define zwp_primary_selection_device_manager_v1
    (make-wl-interface
      "zwp_primary_selection_device_manager_v1"
      1))
  (define zwp_primary_selection_device_v1
    (make-wl-interface "zwp_primary_selection_device_v1" 1))
  (define zwp_primary_selection_offer_v1
    (make-wl-interface "zwp_primary_selection_offer_v1" 1))
  (define zwp_primary_selection_source_v1
    (make-wl-interface "zwp_primary_selection_source_v1" 1))
  (define wp_cursor_shape_manager_v1
    (make-wl-interface "wp_cursor_shape_manager_v1" 2))
  (define wp_cursor_shape_device_v1
    (make-wl-interface "wp_cursor_shape_device_v1" 2))
  (define messages-initialized
    (begin
      (wl-interface-set-messages!
        wl_display
        (vector
          (list "sync" "n" (list wl_callback))
          (list "get_registry" "n" (list wl_registry)))
        (vector
          (list "error" "ous" (list #f #f #f))
          (list "delete_id" "u" (list #f))))
      (wl-interface-set-messages!
        wl_registry
        (vector (list "bind" "usun" (list #f #f #f #f)))
        (vector
          (list "global" "usu" (list #f #f #f))
          (list "global_remove" "u" (list #f))))
      (wl-interface-set-messages!
        wl_callback
        (vector)
        (vector (list "done" "u" (list #f))))
      (wl-interface-set-messages!
        wl_compositor
        (vector
          (list "create_surface" "n" (list wl_surface))
          (list "create_region" "n" (list wl_region)))
        (vector))
      (wl-interface-set-messages!
        wl_shm_pool
        (vector
          (list
            "create_buffer"
            "niiiiu"
            (list wl_buffer #f #f #f #f #f))
          (list "destroy" "" (list))
          (list "resize" "i" (list #f)))
        (vector))
      (wl-interface-set-messages!
        wl_shm
        (vector (list "create_pool" "nhi" (list wl_shm_pool #f #f)))
        (vector (list "format" "u" (list #f))))
      (wl-interface-set-messages!
        wl_buffer
        (vector (list "destroy" "" (list)))
        (vector (list "release" "" (list))))
      (wl-interface-set-messages!
        wl_data_offer
        (vector (list "accept" "u?s" (list #f #f))
          (list "receive" "sh" (list #f #f))
          (list "destroy" "" (list)) (list "finish" "3" (list))
          (list "set_actions" "3uu" (list #f #f)))
        (vector
          (list "offer" "s" (list #f))
          (list "source_actions" "3u" (list #f))
          (list "action" "3u" (list #f))))
      (wl-interface-set-messages!
        wl_data_source
        (vector
          (list "offer" "s" (list #f))
          (list "destroy" "" (list))
          (list "set_actions" "3u" (list #f)))
        (vector (list "target" "?s" (list #f))
          (list "send" "sh" (list #f #f)) (list "cancelled" "" (list))
          (list "dnd_drop_performed" "3" (list))
          (list "dnd_finished" "3" (list))
          (list "action" "3u" (list #f))))
      (wl-interface-set-messages!
        wl_data_device
        (vector
          (list
            "start_drag"
            "?oo?ou"
            (list wl_data_source wl_surface wl_surface #f))
          (list "set_selection" "?ou" (list wl_data_source #f))
          (list "release" "2" (list)))
        (vector (list "data_offer" "n" (list wl_data_offer))
          (list
            "enter"
            "uoff?o"
            (list #f wl_surface #f #f wl_data_offer))
          (list "leave" "" (list))
          (list "motion" "uff" (list #f #f #f))
          (list "drop" "" (list))
          (list "selection" "?o" (list wl_data_offer))))
      (wl-interface-set-messages!
        wl_data_device_manager
        (vector
          (list "create_data_source" "n" (list wl_data_source))
          (list "get_data_device" "no" (list wl_data_device wl_seat)))
        (vector))
      (wl-interface-set-messages!
        wl_shell
        (vector
          (list
            "get_shell_surface"
            "no"
            (list wl_shell_surface wl_surface)))
        (vector))
      (wl-interface-set-messages!
        wl_shell_surface
        (vector (list "pong" "u" (list #f))
          (list "move" "ou" (list wl_seat #f))
          (list "resize" "ouu" (list wl_seat #f #f))
          (list "set_toplevel" "" (list))
          (list "set_transient" "oiiu" (list wl_surface #f #f #f))
          (list "set_fullscreen" "uu?o" (list #f #f wl_output))
          (list
            "set_popup"
            "ouoiiu"
            (list wl_seat #f wl_surface #f #f #f))
          (list "set_maximized" "?o" (list wl_output))
          (list "set_title" "s" (list #f))
          (list "set_class" "s" (list #f)))
        (vector
          (list "ping" "u" (list #f))
          (list "configure" "uii" (list #f #f #f))
          (list "popup_done" "" (list))))
      (wl-interface-set-messages!
        wl_surface
        (vector (list "destroy" "" (list))
          (list "attach" "?oii" (list wl_buffer #f #f))
          (list "damage" "iiii" (list #f #f #f #f))
          (list "frame" "n" (list wl_callback))
          (list "set_opaque_region" "?o" (list wl_region))
          (list "set_input_region" "?o" (list wl_region))
          (list "commit" "" (list))
          (list "set_buffer_transform" "2i" (list #f))
          (list "set_buffer_scale" "3i" (list #f))
          (list "damage_buffer" "4iiii" (list #f #f #f #f))
          (list "offset" "5ii" (list #f #f)))
        (vector
          (list "enter" "o" (list wl_output))
          (list "leave" "o" (list wl_output))
          (list "preferred_buffer_scale" "6i" (list #f))
          (list "preferred_buffer_transform" "6u" (list #f))))
      (wl-interface-set-messages!
        wl_seat
        (vector
          (list "get_pointer" "n" (list wl_pointer))
          (list "get_keyboard" "n" (list wl_keyboard))
          (list "get_touch" "n" (list wl_touch))
          (list "release" "5" (list)))
        (vector
          (list "capabilities" "u" (list #f))
          (list "name" "2s" (list #f))))
      (wl-interface-set-messages!
        wl_pointer
        (vector
          (list "set_cursor" "u?oii" (list #f wl_surface #f #f))
          (list "release" "3" (list)))
        (vector (list "enter" "uoff" (list #f wl_surface #f #f))
          (list "leave" "uo" (list #f wl_surface))
          (list "motion" "uff" (list #f #f #f))
          (list "button" "uuuu" (list #f #f #f #f))
          (list "axis" "uuf" (list #f #f #f))
          (list "frame" "5" (list))
          (list "axis_source" "5u" (list #f))
          (list "axis_stop" "5uu" (list #f #f))
          (list "axis_discrete" "5ui" (list #f #f))
          (list "axis_value120" "8ui" (list #f #f))
          (list "axis_relative_direction" "9uu" (list #f #f))))
      (wl-interface-set-messages!
        wl_keyboard
        (vector (list "release" "3" (list)))
        (vector (list "keymap" "uhu" (list #f #f #f))
          (list "enter" "uoa" (list #f wl_surface #f))
          (list "leave" "uo" (list #f wl_surface))
          (list "key" "uuuu" (list #f #f #f #f))
          (list "modifiers" "uuuuu" (list #f #f #f #f #f))
          (list "repeat_info" "4ii" (list #f #f))))
      (wl-interface-set-messages!
        wl_touch
        (vector (list "release" "3" (list)))
        (vector (list "down" "uuoiff" (list #f #f wl_surface #f #f #f))
          (list "up" "uui" (list #f #f #f))
          (list "motion" "uiff" (list #f #f #f #f))
          (list "frame" "" (list)) (list "cancel" "" (list))
          (list "shape" "6iff" (list #f #f #f))
          (list "orientation" "6if" (list #f #f))))
      (wl-interface-set-messages!
        wl_output
        (vector (list "release" "3" (list)))
        (vector (list "geometry" "iiiiissi" (list #f #f #f #f #f #f #f #f))
          (list "mode" "uiii" (list #f #f #f #f))
          (list "done" "2" (list)) (list "scale" "2i" (list #f))
          (list "name" "4s" (list #f))
          (list "description" "4s" (list #f))))
      (wl-interface-set-messages!
        wl_region
        (vector
          (list "destroy" "" (list))
          (list "add" "iiii" (list #f #f #f #f))
          (list "subtract" "iiii" (list #f #f #f #f)))
        (vector))
      (wl-interface-set-messages!
        wl_subcompositor
        (vector
          (list "destroy" "" (list))
          (list
            "get_subsurface"
            "noo"
            (list wl_subsurface wl_surface wl_surface)))
        (vector))
      (wl-interface-set-messages!
        wl_subsurface
        (vector (list "destroy" "" (list))
          (list "set_position" "ii" (list #f #f))
          (list "place_above" "o" (list wl_surface))
          (list "place_below" "o" (list wl_surface))
          (list "set_sync" "" (list)) (list "set_desync" "" (list)))
        (vector))
      (wl-interface-set-messages!
        xdg_wm_base
        (vector
          (list "destroy" "" (list))
          (list "create_positioner" "n" (list xdg_positioner))
          (list "get_xdg_surface" "no" (list xdg_surface wl_surface))
          (list "pong" "u" (list #f)))
        (vector (list "ping" "u" (list #f))))
      (wl-interface-set-messages!
        xdg_positioner
        (vector (list "destroy" "" (list))
          (list "set_size" "ii" (list #f #f))
          (list "set_anchor_rect" "iiii" (list #f #f #f #f))
          (list "set_anchor" "u" (list #f))
          (list "set_gravity" "u" (list #f))
          (list "set_constraint_adjustment" "u" (list #f))
          (list "set_offset" "ii" (list #f #f))
          (list "set_reactive" "3" (list))
          (list "set_parent_size" "3ii" (list #f #f))
          (list "set_parent_configure" "3u" (list #f)))
        (vector))
      (wl-interface-set-messages!
        xdg_surface
        (vector (list "destroy" "" (list))
          (list "get_toplevel" "n" (list xdg_toplevel))
          (list
            "get_popup"
            "n?oo"
            (list xdg_popup xdg_surface xdg_positioner))
          (list "set_window_geometry" "iiii" (list #f #f #f #f))
          (list "ack_configure" "u" (list #f)))
        (vector (list "configure" "u" (list #f))))
      (wl-interface-set-messages!
        xdg_toplevel
        (vector (list "destroy" "" (list))
          (list "set_parent" "?o" (list xdg_toplevel))
          (list "set_title" "s" (list #f))
          (list "set_app_id" "s" (list #f))
          (list "show_window_menu" "ouii" (list wl_seat #f #f #f))
          (list "move" "ou" (list wl_seat #f))
          (list "resize" "ouu" (list wl_seat #f #f))
          (list "set_max_size" "ii" (list #f #f))
          (list "set_min_size" "ii" (list #f #f))
          (list "set_maximized" "" (list))
          (list "unset_maximized" "" (list))
          (list "set_fullscreen" "?o" (list wl_output))
          (list "unset_fullscreen" "" (list))
          (list "set_minimized" "" (list)))
        (vector
          (list "configure" "iia" (list #f #f #f))
          (list "close" "" (list))
          (list "configure_bounds" "4ii" (list #f #f))
          (list "wm_capabilities" "5a" (list #f))))
      (wl-interface-set-messages!
        xdg_popup
        (vector
          (list "destroy" "" (list))
          (list "grab" "ou" (list wl_seat #f))
          (list "reposition" "3ou" (list xdg_positioner #f)))
        (vector
          (list "configure" "iiii" (list #f #f #f #f))
          (list "popup_done" "" (list))
          (list "repositioned" "3u" (list #f))))
      (wl-interface-set-messages!
        zxdg_decoration_manager_v1
        (vector
          (list "destroy" "" (list))
          (list
            "get_toplevel_decoration"
            "no"
            (list zxdg_toplevel_decoration_v1 xdg_toplevel)))
        (vector))
      (wl-interface-set-messages!
        zxdg_toplevel_decoration_v1
        (vector
          (list "destroy" "" (list))
          (list "set_mode" "u" (list #f))
          (list "unset_mode" "" (list)))
        (vector (list "configure" "u" (list #f))))
      (wl-interface-set-messages!
        zwp_primary_selection_device_manager_v1
        (vector
          (list
            "create_source"
            "n"
            (list zwp_primary_selection_source_v1))
          (list
            "get_device"
            "no"
            (list zwp_primary_selection_device_v1 wl_seat))
          (list "destroy" "" (list)))
        (vector))
      (wl-interface-set-messages!
        zwp_primary_selection_device_v1
        (vector
          (list
            "set_selection"
            "?ou"
            (list zwp_primary_selection_source_v1 #f))
          (list "destroy" "" (list)))
        (vector
          (list
            "data_offer"
            "n"
            (list zwp_primary_selection_offer_v1))
          (list
            "selection"
            "?o"
            (list zwp_primary_selection_offer_v1))))
      (wl-interface-set-messages!
        zwp_primary_selection_offer_v1
        (vector
          (list "receive" "sh" (list #f #f))
          (list "destroy" "" (list)))
        (vector (list "offer" "s" (list #f))))
      (wl-interface-set-messages!
        zwp_primary_selection_source_v1
        (vector
          (list "offer" "s" (list #f))
          (list "destroy" "" (list)))
        (vector
          (list "send" "sh" (list #f #f))
          (list "cancelled" "" (list))))
      (wl-interface-set-messages!
        wp_cursor_shape_manager_v1
        (vector
          (list "destroy" "" (list))
          (list
            "get_pointer"
            "no"
            (list wp_cursor_shape_device_v1 wl_pointer))
          (list
            "get_tablet_tool_v2"
            "no"
            (list wp_cursor_shape_device_v1 #f)))
        (vector))
      (wl-interface-set-messages!
        wp_cursor_shape_device_v1
        (vector
          (list "destroy" "" (list))
          (list "set_shape" "uu" (list #f #f)))
        (vector))
      #t))
  (define (wl_display_sync proxy)
    (wl-marshal proxy wl_display 0 wl_callback #f 0 0))
  (define (wl_display_get_registry proxy)
    (wl-marshal proxy wl_display 1 wl_registry #f 0 0))
  (define (wl_registry_bind proxy name interface version)
    (wl-marshal proxy wl_registry 0 interface version 0 name
      (wl-interface-name interface) version 0))
  (define (wl_registry_destroy proxy)
    (wl-proxy-destroy proxy))
  (define (wl_callback_destroy proxy)
    (wl-proxy-destroy proxy))
  (define (wl_compositor_create_surface proxy)
    (wl-marshal proxy wl_compositor 0 wl_surface #f 0 0))
  (define (wl_compositor_create_region proxy)
    (wl-marshal proxy wl_compositor 1 wl_region #f 0 0))
  (define (wl_compositor_destroy proxy)
    (wl-proxy-destroy proxy))
  (define (wl_shm_pool_create_buffer proxy offset width height
           stride format)
    (wl-marshal proxy wl_shm_pool 0 wl_buffer #f 0 0 offset
      width height stride format))
  (define (wl_shm_pool_destroy proxy)
    (wl-marshal proxy wl_shm_pool 1 #f #f 1))
  (define (wl_shm_pool_resize proxy size)
    (wl-marshal proxy wl_shm_pool 2 #f #f 0 size))
  (define (wl_shm_create_pool proxy fd size)
    (wl-marshal proxy wl_shm 0 wl_shm_pool #f 0 0 fd size))
  (define (wl_shm_destroy proxy) (wl-proxy-destroy proxy))
  (define (wl_buffer_destroy proxy)
    (wl-marshal proxy wl_buffer 0 #f #f 1))
  (define (wl_data_offer_accept proxy serial mime_type)
    (wl-marshal proxy wl_data_offer 0 #f #f 0 serial mime_type))
  (define (wl_data_offer_receive proxy mime_type fd)
    (wl-marshal proxy wl_data_offer 1 #f #f 0 mime_type fd))
  (define (wl_data_offer_destroy proxy)
    (wl-marshal proxy wl_data_offer 2 #f #f 1))
  (define (wl_data_offer_finish proxy)
    (wl-marshal proxy wl_data_offer 3 #f #f 0))
  (define (wl_data_offer_set_actions proxy dnd_actions
           preferred_action)
    (wl-marshal proxy wl_data_offer 4 #f #f 0 dnd_actions
      preferred_action))
  (define (wl_data_source_offer proxy mime_type)
    (wl-marshal proxy wl_data_source 0 #f #f 0 mime_type))
  (define (wl_data_source_destroy proxy)
    (wl-marshal proxy wl_data_source 1 #f #f 1))
  (define (wl_data_source_set_actions proxy dnd_actions)
    (wl-marshal proxy wl_data_source 2 #f #f 0 dnd_actions))
  (define (wl_data_device_start_drag proxy source origin icon
           serial)
    (wl-marshal proxy wl_data_device 0 #f #f 0 source origin
      icon serial))
  (define (wl_data_device_set_selection proxy source serial)
    (wl-marshal proxy wl_data_device 1 #f #f 0 source serial))
  (define (wl_data_device_release proxy)
    (wl-marshal proxy wl_data_device 2 #f #f 1))
  (define (wl_data_device_destroy proxy)
    (wl-proxy-destroy proxy))
  (define (wl_data_device_manager_create_data_source proxy)
    (wl-marshal proxy wl_data_device_manager 0 wl_data_source #f
      0 0))
  (define (wl_data_device_manager_get_data_device proxy seat)
    (wl-marshal proxy wl_data_device_manager 1 wl_data_device #f
      0 0 seat))
  (define (wl_data_device_manager_destroy proxy)
    (wl-proxy-destroy proxy))
  (define (wl_shell_get_shell_surface proxy surface)
    (wl-marshal proxy wl_shell 0 wl_shell_surface #f 0 0
      surface))
  (define (wl_shell_destroy proxy) (wl-proxy-destroy proxy))
  (define (wl_shell_surface_pong proxy serial)
    (wl-marshal proxy wl_shell_surface 0 #f #f 0 serial))
  (define (wl_shell_surface_move proxy seat serial)
    (wl-marshal proxy wl_shell_surface 1 #f #f 0 seat serial))
  (define (wl_shell_surface_resize proxy seat serial edges)
    (wl-marshal proxy wl_shell_surface 2 #f #f 0 seat serial
      edges))
  (define (wl_shell_surface_set_toplevel proxy)
    (wl-marshal proxy wl_shell_surface 3 #f #f 0))
  (define (wl_shell_surface_set_transient proxy parent x y
           flags)
    (wl-marshal proxy wl_shell_surface 4 #f #f 0 parent x y
      flags))
  (define (wl_shell_surface_set_fullscreen proxy method
           framerate output)
    (wl-marshal proxy wl_shell_surface 5 #f #f 0 method
      framerate output))
  (define (wl_shell_surface_set_popup proxy seat serial parent
           x y flags)
    (wl-marshal proxy wl_shell_surface 6 #f #f 0 seat serial
      parent x y flags))
  (define (wl_shell_surface_set_maximized proxy output)
    (wl-marshal proxy wl_shell_surface 7 #f #f 0 output))
  (define (wl_shell_surface_set_title proxy title)
    (wl-marshal proxy wl_shell_surface 8 #f #f 0 title))
  (define (wl_shell_surface_set_class proxy class_)
    (wl-marshal proxy wl_shell_surface 9 #f #f 0 class_))
  (define (wl_shell_surface_destroy proxy)
    (wl-proxy-destroy proxy))
  (define (wl_surface_destroy proxy)
    (wl-marshal proxy wl_surface 0 #f #f 1))
  (define (wl_surface_attach proxy buffer x y)
    (wl-marshal proxy wl_surface 1 #f #f 0 buffer x y))
  (define (wl_surface_damage proxy x y width height)
    (wl-marshal proxy wl_surface 2 #f #f 0 x y width height))
  (define (wl_surface_frame proxy)
    (wl-marshal proxy wl_surface 3 wl_callback #f 0 0))
  (define (wl_surface_set_opaque_region proxy region)
    (wl-marshal proxy wl_surface 4 #f #f 0 region))
  (define (wl_surface_set_input_region proxy region)
    (wl-marshal proxy wl_surface 5 #f #f 0 region))
  (define (wl_surface_commit proxy)
    (wl-marshal proxy wl_surface 6 #f #f 0))
  (define (wl_surface_set_buffer_transform proxy transform)
    (wl-marshal proxy wl_surface 7 #f #f 0 transform))
  (define (wl_surface_set_buffer_scale proxy scale)
    (wl-marshal proxy wl_surface 8 #f #f 0 scale))
  (define (wl_surface_damage_buffer proxy x y width height)
    (wl-marshal proxy wl_surface 9 #f #f 0 x y width height))
  (define (wl_surface_offset proxy x y)
    (wl-marshal proxy wl_surface 10 #f #f 0 x y))
  (define (wl_seat_get_pointer proxy)
    (wl-marshal proxy wl_seat 0 wl_pointer #f 0 0))
  (define (wl_seat_get_keyboard proxy)
    (wl-marshal proxy wl_seat 1 wl_keyboard #f 0 0))
  (define (wl_seat_get_touch proxy)
    (wl-marshal proxy wl_seat 2 wl_touch #f 0 0))
  (define (wl_seat_release proxy)
    (wl-marshal proxy wl_seat 3 #f #f 1))
  (define (wl_seat_destroy proxy) (wl-proxy-destroy proxy))
  (define (wl_pointer_set_cursor proxy serial surface
           hotspot_x hotspot_y)
    (wl-marshal proxy wl_pointer 0 #f #f 0 serial surface
      hotspot_x hotspot_y))
  (define (wl_pointer_release proxy)
    (wl-marshal proxy wl_pointer 1 #f #f 1))
  (define (wl_pointer_destroy proxy) (wl-proxy-destroy proxy))
  (define (wl_keyboard_release proxy)
    (wl-marshal proxy wl_keyboard 0 #f #f 1))
  (define (wl_keyboard_destroy proxy)
    (wl-proxy-destroy proxy))
  (define (wl_touch_release proxy)
    (wl-marshal proxy wl_touch 0 #f #f 1))
  (define (wl_touch_destroy proxy) (wl-proxy-destroy proxy))
  (define (wl_output_release proxy)
    (wl-marshal proxy wl_output 0 #f #f 1))
  (define (wl_output_destroy proxy) (wl-proxy-destroy proxy))
  (define (wl_region_destroy proxy)
    (wl-marshal proxy wl_region 0 #f #f 1))
  (define (wl_region_add proxy x y width height)
    (wl-marshal proxy wl_region 1 #f #f 0 x y width height))
  (define (wl_region_subtract proxy x y width height)
    (wl-marshal proxy wl_region 2 #f #f 0 x y width height))
  (define (wl_subcompositor_destroy proxy)
    (wl-marshal proxy wl_subcompositor 0 #f #f 1))
  (define (wl_subcompositor_get_subsurface proxy surface
           parent)
    (wl-marshal proxy wl_subcompositor 1 wl_subsurface #f 0 0
      surface parent))
  (define (wl_subsurface_destroy proxy)
    (wl-marshal proxy wl_subsurface 0 #f #f 1))
  (define (wl_subsurface_set_position proxy x y)
    (wl-marshal proxy wl_subsurface 1 #f #f 0 x y))
  (define (wl_subsurface_place_above proxy sibling)
    (wl-marshal proxy wl_subsurface 2 #f #f 0 sibling))
  (define (wl_subsurface_place_below proxy sibling)
    (wl-marshal proxy wl_subsurface 3 #f #f 0 sibling))
  (define (wl_subsurface_set_sync proxy)
    (wl-marshal proxy wl_subsurface 4 #f #f 0))
  (define (wl_subsurface_set_desync proxy)
    (wl-marshal proxy wl_subsurface 5 #f #f 0))
  (define (xdg_wm_base_destroy proxy)
    (wl-marshal proxy xdg_wm_base 0 #f #f 1))
  (define (xdg_wm_base_create_positioner proxy)
    (wl-marshal proxy xdg_wm_base 1 xdg_positioner #f 0 0))
  (define (xdg_wm_base_get_xdg_surface proxy surface)
    (wl-marshal proxy xdg_wm_base 2 xdg_surface #f 0 0 surface))
  (define (xdg_wm_base_pong proxy serial)
    (wl-marshal proxy xdg_wm_base 3 #f #f 0 serial))
  (define (xdg_positioner_destroy proxy)
    (wl-marshal proxy xdg_positioner 0 #f #f 1))
  (define (xdg_positioner_set_size proxy width height)
    (wl-marshal proxy xdg_positioner 1 #f #f 0 width height))
  (define (xdg_positioner_set_anchor_rect proxy x y width
           height)
    (wl-marshal proxy xdg_positioner 2 #f #f 0 x y width
      height))
  (define (xdg_positioner_set_anchor proxy anchor)
    (wl-marshal proxy xdg_positioner 3 #f #f 0 anchor))
  (define (xdg_positioner_set_gravity proxy gravity)
    (wl-marshal proxy xdg_positioner 4 #f #f 0 gravity))
  (define (xdg_positioner_set_constraint_adjustment proxy
           constraint_adjustment)
    (wl-marshal proxy xdg_positioner 5 #f #f 0
      constraint_adjustment))
  (define (xdg_positioner_set_offset proxy x y)
    (wl-marshal proxy xdg_positioner 6 #f #f 0 x y))
  (define (xdg_positioner_set_reactive proxy)
    (wl-marshal proxy xdg_positioner 7 #f #f 0))
  (define (xdg_positioner_set_parent_size proxy parent_width
           parent_height)
    (wl-marshal proxy xdg_positioner 8 #f #f 0 parent_width
      parent_height))
  (define (xdg_positioner_set_parent_configure proxy serial)
    (wl-marshal proxy xdg_positioner 9 #f #f 0 serial))
  (define (xdg_surface_destroy proxy)
    (wl-marshal proxy xdg_surface 0 #f #f 1))
  (define (xdg_surface_get_toplevel proxy)
    (wl-marshal proxy xdg_surface 1 xdg_toplevel #f 0 0))
  (define (xdg_surface_get_popup proxy parent positioner)
    (wl-marshal proxy xdg_surface 2 xdg_popup #f 0 0 parent
      positioner))
  (define (xdg_surface_set_window_geometry proxy x y width
           height)
    (wl-marshal proxy xdg_surface 3 #f #f 0 x y width height))
  (define (xdg_surface_ack_configure proxy serial)
    (wl-marshal proxy xdg_surface 4 #f #f 0 serial))
  (define (xdg_toplevel_destroy proxy)
    (wl-marshal proxy xdg_toplevel 0 #f #f 1))
  (define (xdg_toplevel_set_parent proxy parent)
    (wl-marshal proxy xdg_toplevel 1 #f #f 0 parent))
  (define (xdg_toplevel_set_title proxy title)
    (wl-marshal proxy xdg_toplevel 2 #f #f 0 title))
  (define (xdg_toplevel_set_app_id proxy app_id)
    (wl-marshal proxy xdg_toplevel 3 #f #f 0 app_id))
  (define (xdg_toplevel_show_window_menu proxy seat serial x
           y)
    (wl-marshal proxy xdg_toplevel 4 #f #f 0 seat serial x y))
  (define (xdg_toplevel_move proxy seat serial)
    (wl-marshal proxy xdg_toplevel 5 #f #f 0 seat serial))
  (define (xdg_toplevel_resize proxy seat serial edges)
    (wl-marshal proxy xdg_toplevel 6 #f #f 0 seat serial edges))
  (define (xdg_toplevel_set_max_size proxy width height)
    (wl-marshal proxy xdg_toplevel 7 #f #f 0 width height))
  (define (xdg_toplevel_set_min_size proxy width height)
    (wl-marshal proxy xdg_toplevel 8 #f #f 0 width height))
  (define (xdg_toplevel_set_maximized proxy)
    (wl-marshal proxy xdg_toplevel 9 #f #f 0))
  (define (xdg_toplevel_unset_maximized proxy)
    (wl-marshal proxy xdg_toplevel 10 #f #f 0))
  (define (xdg_toplevel_set_fullscreen proxy output)
    (wl-marshal proxy xdg_toplevel 11 #f #f 0 output))
  (define (xdg_toplevel_unset_fullscreen proxy)
    (wl-marshal proxy xdg_toplevel 12 #f #f 0))
  (define (xdg_toplevel_set_minimized proxy)
    (wl-marshal proxy xdg_toplevel 13 #f #f 0))
  (define (xdg_popup_destroy proxy)
    (wl-marshal proxy xdg_popup 0 #f #f 1))
  (define (xdg_popup_grab proxy seat serial)
    (wl-marshal proxy xdg_popup 1 #f #f 0 seat serial))
  (define (xdg_popup_reposition proxy positioner token)
    (wl-marshal proxy xdg_popup 2 #f #f 0 positioner token))
  (define (zxdg_decoration_manager_v1_destroy proxy)
    (wl-marshal proxy zxdg_decoration_manager_v1 0 #f #f 1))
  (define (zxdg_decoration_manager_v1_get_toplevel_decoration
           proxy toplevel)
    (wl-marshal proxy zxdg_decoration_manager_v1 1
      zxdg_toplevel_decoration_v1 #f 0 0 toplevel))
  (define (zxdg_toplevel_decoration_v1_destroy proxy)
    (wl-marshal proxy zxdg_toplevel_decoration_v1 0 #f #f 1))
  (define (zxdg_toplevel_decoration_v1_set_mode proxy mode)
    (wl-marshal proxy zxdg_toplevel_decoration_v1 1 #f #f 0
      mode))
  (define (zxdg_toplevel_decoration_v1_unset_mode proxy)
    (wl-marshal proxy zxdg_toplevel_decoration_v1 2 #f #f 0))
  (define (zwp_primary_selection_device_manager_v1_create_source
           proxy)
    (wl-marshal proxy zwp_primary_selection_device_manager_v1 0
      zwp_primary_selection_source_v1 #f 0 0))
  (define (zwp_primary_selection_device_manager_v1_get_device
           proxy seat)
    (wl-marshal proxy zwp_primary_selection_device_manager_v1 1
      zwp_primary_selection_device_v1 #f 0 0 seat))
  (define (zwp_primary_selection_device_manager_v1_destroy
           proxy)
    (wl-marshal proxy zwp_primary_selection_device_manager_v1 2
      #f #f 1))
  (define (zwp_primary_selection_device_v1_set_selection proxy
           source serial)
    (wl-marshal proxy zwp_primary_selection_device_v1 0 #f #f 0
      source serial))
  (define (zwp_primary_selection_device_v1_destroy proxy)
    (wl-marshal proxy zwp_primary_selection_device_v1 1 #f #f
      1))
  (define (zwp_primary_selection_offer_v1_receive proxy
           mime_type fd)
    (wl-marshal proxy zwp_primary_selection_offer_v1 0 #f #f 0
      mime_type fd))
  (define (zwp_primary_selection_offer_v1_destroy proxy)
    (wl-marshal proxy zwp_primary_selection_offer_v1 1 #f #f 1))
  (define (zwp_primary_selection_source_v1_offer proxy
           mime_type)
    (wl-marshal proxy zwp_primary_selection_source_v1 0 #f #f 0
      mime_type))
  (define (zwp_primary_selection_source_v1_destroy proxy)
    (wl-marshal proxy zwp_primary_selection_source_v1 1 #f #f
      1))
  (define (wp_cursor_shape_manager_v1_destroy proxy)
    (wl-marshal proxy wp_cursor_shape_manager_v1 0 #f #f 1))
  (define (wp_cursor_shape_manager_v1_get_pointer proxy
           pointer)
    (wl-marshal proxy wp_cursor_shape_manager_v1 1
      wp_cursor_shape_device_v1 #f 0 0 pointer))
  (define (wp_cursor_shape_manager_v1_get_tablet_tool_v2 proxy
           tablet_tool)
    (wl-marshal proxy wp_cursor_shape_manager_v1 2
      wp_cursor_shape_device_v1 #f 0 0 tablet_tool))
  (define (wp_cursor_shape_device_v1_destroy proxy)
    (wl-marshal proxy wp_cursor_shape_device_v1 0 #f #f 1))
  (define (wp_cursor_shape_device_v1_set_shape proxy serial
           shape)
    (wl-marshal proxy wp_cursor_shape_device_v1 1 #f #f 0 serial
      shape))
  (define WL_DISPLAY_ERROR_INVALID_OBJECT 0)
  (define WL_DISPLAY_ERROR_INVALID_METHOD 1)
  (define WL_DISPLAY_ERROR_NO_MEMORY 2)
  (define WL_DISPLAY_ERROR_IMPLEMENTATION 3)
  (define WL_SHM_ERROR_INVALID_FORMAT 0)
  (define WL_SHM_ERROR_INVALID_STRIDE 1)
  (define WL_SHM_ERROR_INVALID_FD 2)
  (define WL_SHM_FORMAT_ARGB8888 0)
  (define WL_SHM_FORMAT_XRGB8888 1)
  (define WL_SHM_FORMAT_C8 538982467)
  (define WL_SHM_FORMAT_RGB332 943867730)
  (define WL_SHM_FORMAT_BGR233 944916290)
  (define WL_SHM_FORMAT_XRGB4444 842093144)
  (define WL_SHM_FORMAT_XBGR4444 842089048)
  (define WL_SHM_FORMAT_RGBX4444 842094674)
  (define WL_SHM_FORMAT_BGRX4444 842094658)
  (define WL_SHM_FORMAT_ARGB4444 842093121)
  (define WL_SHM_FORMAT_ABGR4444 842089025)
  (define WL_SHM_FORMAT_RGBA4444 842088786)
  (define WL_SHM_FORMAT_BGRA4444 842088770)
  (define WL_SHM_FORMAT_XRGB1555 892424792)
  (define WL_SHM_FORMAT_XBGR1555 892420696)
  (define WL_SHM_FORMAT_RGBX5551 892426322)
  (define WL_SHM_FORMAT_BGRX5551 892426306)
  (define WL_SHM_FORMAT_ARGB1555 892424769)
  (define WL_SHM_FORMAT_ABGR1555 892420673)
  (define WL_SHM_FORMAT_RGBA5551 892420434)
  (define WL_SHM_FORMAT_BGRA5551 892420418)
  (define WL_SHM_FORMAT_RGB565 909199186)
  (define WL_SHM_FORMAT_BGR565 909199170)
  (define WL_SHM_FORMAT_RGB888 875710290)
  (define WL_SHM_FORMAT_BGR888 875710274)
  (define WL_SHM_FORMAT_XBGR8888 875709016)
  (define WL_SHM_FORMAT_RGBX8888 875714642)
  (define WL_SHM_FORMAT_BGRX8888 875714626)
  (define WL_SHM_FORMAT_ABGR8888 875708993)
  (define WL_SHM_FORMAT_RGBA8888 875708754)
  (define WL_SHM_FORMAT_BGRA8888 875708738)
  (define WL_SHM_FORMAT_XRGB2101010 808669784)
  (define WL_SHM_FORMAT_XBGR2101010 808665688)
  (define WL_SHM_FORMAT_RGBX1010102 808671314)
  (define WL_SHM_FORMAT_BGRX1010102 808671298)
  (define WL_SHM_FORMAT_ARGB2101010 808669761)
  (define WL_SHM_FORMAT_ABGR2101010 808665665)
  (define WL_SHM_FORMAT_RGBA1010102 808665426)
  (define WL_SHM_FORMAT_BGRA1010102 808665410)
  (define WL_SHM_FORMAT_YUYV 1448695129)
  (define WL_SHM_FORMAT_YVYU 1431918169)
  (define WL_SHM_FORMAT_UYVY 1498831189)
  (define WL_SHM_FORMAT_VYUY 1498765654)
  (define WL_SHM_FORMAT_AYUV 1448433985)
  (define WL_SHM_FORMAT_NV12 842094158)
  (define WL_SHM_FORMAT_NV21 825382478)
  (define WL_SHM_FORMAT_NV16 909203022)
  (define WL_SHM_FORMAT_NV61 825644622)
  (define WL_SHM_FORMAT_YUV410 961959257)
  (define WL_SHM_FORMAT_YVU410 961893977)
  (define WL_SHM_FORMAT_YUV411 825316697)
  (define WL_SHM_FORMAT_YVU411 825316953)
  (define WL_SHM_FORMAT_YUV420 842093913)
  (define WL_SHM_FORMAT_YVU420 842094169)
  (define WL_SHM_FORMAT_YUV422 909202777)
  (define WL_SHM_FORMAT_YVU422 909203033)
  (define WL_SHM_FORMAT_YUV444 875713881)
  (define WL_SHM_FORMAT_YVU444 875714137)
  (define WL_SHM_FORMAT_R8 538982482)
  (define WL_SHM_FORMAT_R16 540422482)
  (define WL_SHM_FORMAT_RG88 943212370)
  (define WL_SHM_FORMAT_GR88 943215175)
  (define WL_SHM_FORMAT_RG1616 842221394)
  (define WL_SHM_FORMAT_GR1616 842224199)
  (define WL_SHM_FORMAT_XRGB16161616F 1211388504)
  (define WL_SHM_FORMAT_XBGR16161616F 1211384408)
  (define WL_SHM_FORMAT_ARGB16161616F 1211388481)
  (define WL_SHM_FORMAT_ABGR16161616F 1211384385)
  (define WL_SHM_FORMAT_XYUV8888 1448434008)
  (define WL_SHM_FORMAT_VUY888 875713878)
  (define WL_SHM_FORMAT_VUY101010 808670550)
  (define WL_SHM_FORMAT_Y210 808530521)
  (define WL_SHM_FORMAT_Y212 842084953)
  (define WL_SHM_FORMAT_Y216 909193817)
  (define WL_SHM_FORMAT_Y410 808531033)
  (define WL_SHM_FORMAT_Y412 842085465)
  (define WL_SHM_FORMAT_Y416 909194329)
  (define WL_SHM_FORMAT_XVYU2101010 808670808)
  (define WL_SHM_FORMAT_XVYU12_16161616 909334104)
  (define WL_SHM_FORMAT_XVYU16161616 942954072)
  (define WL_SHM_FORMAT_Y0L0 810299481)
  (define WL_SHM_FORMAT_X0L0 810299480)
  (define WL_SHM_FORMAT_Y0L2 843853913)
  (define WL_SHM_FORMAT_X0L2 843853912)
  (define WL_SHM_FORMAT_YUV420_8BIT 942691673)
  (define WL_SHM_FORMAT_YUV420_10BIT 808539481)
  (define WL_SHM_FORMAT_XRGB8888_A8 943805016)
  (define WL_SHM_FORMAT_XBGR8888_A8 943800920)
  (define WL_SHM_FORMAT_RGBX8888_A8 943806546)
  (define WL_SHM_FORMAT_BGRX8888_A8 943806530)
  (define WL_SHM_FORMAT_RGB888_A8 943798354)
  (define WL_SHM_FORMAT_BGR888_A8 943798338)
  (define WL_SHM_FORMAT_RGB565_A8 943797586)
  (define WL_SHM_FORMAT_BGR565_A8 943797570)
  (define WL_SHM_FORMAT_NV24 875714126)
  (define WL_SHM_FORMAT_NV42 842290766)
  (define WL_SHM_FORMAT_P210 808530512)
  (define WL_SHM_FORMAT_P010 808530000)
  (define WL_SHM_FORMAT_P012 842084432)
  (define WL_SHM_FORMAT_P016 909193296)
  (define WL_SHM_FORMAT_AXBXGXRX106106106106 808534593)
  (define WL_SHM_FORMAT_NV15 892425806)
  (define WL_SHM_FORMAT_Q410 808531025)
  (define WL_SHM_FORMAT_Q401 825242705)
  (define WL_SHM_FORMAT_XRGB16161616 942953048)
  (define WL_SHM_FORMAT_XBGR16161616 942948952)
  (define WL_SHM_FORMAT_ARGB16161616 942953025)
  (define WL_SHM_FORMAT_ABGR16161616 942948929)
  (define WL_DATA_OFFER_ERROR_INVALID_FINISH 0)
  (define WL_DATA_OFFER_ERROR_INVALID_ACTION_MASK 1)
  (define WL_DATA_OFFER_ERROR_INVALID_ACTION 2)
  (define WL_DATA_OFFER_ERROR_INVALID_OFFER 3)
  (define WL_DATA_SOURCE_ERROR_INVALID_ACTION_MASK 0)
  (define WL_DATA_SOURCE_ERROR_INVALID_SOURCE 1)
  (define WL_DATA_DEVICE_ERROR_ROLE 0)
  (define WL_DATA_DEVICE_MANAGER_DND_ACTION_NONE 0)
  (define WL_DATA_DEVICE_MANAGER_DND_ACTION_COPY 1)
  (define WL_DATA_DEVICE_MANAGER_DND_ACTION_MOVE 2)
  (define WL_DATA_DEVICE_MANAGER_DND_ACTION_ASK 4)
  (define WL_SHELL_ERROR_ROLE 0)
  (define WL_SHELL_SURFACE_RESIZE_NONE 0)
  (define WL_SHELL_SURFACE_RESIZE_TOP 1)
  (define WL_SHELL_SURFACE_RESIZE_BOTTOM 2)
  (define WL_SHELL_SURFACE_RESIZE_LEFT 4)
  (define WL_SHELL_SURFACE_RESIZE_TOP_LEFT 5)
  (define WL_SHELL_SURFACE_RESIZE_BOTTOM_LEFT 6)
  (define WL_SHELL_SURFACE_RESIZE_RIGHT 8)
  (define WL_SHELL_SURFACE_RESIZE_TOP_RIGHT 9)
  (define WL_SHELL_SURFACE_RESIZE_BOTTOM_RIGHT 10)
  (define WL_SHELL_SURFACE_TRANSIENT_INACTIVE 1)
  (define WL_SHELL_SURFACE_FULLSCREEN_METHOD_DEFAULT 0)
  (define WL_SHELL_SURFACE_FULLSCREEN_METHOD_SCALE 1)
  (define WL_SHELL_SURFACE_FULLSCREEN_METHOD_DRIVER 2)
  (define WL_SHELL_SURFACE_FULLSCREEN_METHOD_FILL 3)
  (define WL_SURFACE_ERROR_INVALID_SCALE 0)
  (define WL_SURFACE_ERROR_INVALID_TRANSFORM 1)
  (define WL_SURFACE_ERROR_INVALID_SIZE 2)
  (define WL_SURFACE_ERROR_INVALID_OFFSET 3)
  (define WL_SURFACE_ERROR_DEFUNCT_ROLE_OBJECT 4)
  (define WL_SEAT_CAPABILITY_POINTER 1)
  (define WL_SEAT_CAPABILITY_KEYBOARD 2)
  (define WL_SEAT_CAPABILITY_TOUCH 4)
  (define WL_SEAT_ERROR_MISSING_CAPABILITY 0)
  (define WL_POINTER_ERROR_ROLE 0)
  (define WL_POINTER_BUTTON_STATE_RELEASED 0)
  (define WL_POINTER_BUTTON_STATE_PRESSED 1)
  (define WL_POINTER_AXIS_VERTICAL_SCROLL 0)
  (define WL_POINTER_AXIS_HORIZONTAL_SCROLL 1)
  (define WL_POINTER_AXIS_SOURCE_WHEEL 0)
  (define WL_POINTER_AXIS_SOURCE_FINGER 1)
  (define WL_POINTER_AXIS_SOURCE_CONTINUOUS 2)
  (define WL_POINTER_AXIS_SOURCE_WHEEL_TILT 3)
  (define WL_POINTER_AXIS_RELATIVE_DIRECTION_IDENTICAL 0)
  (define WL_POINTER_AXIS_RELATIVE_DIRECTION_INVERTED 1)
  (define WL_KEYBOARD_KEYMAP_FORMAT_NO_KEYMAP 0)
  (define WL_KEYBOARD_KEYMAP_FORMAT_XKB_V1 1)
  (define WL_KEYBOARD_KEY_STATE_RELEASED 0)
  (define WL_KEYBOARD_KEY_STATE_PRESSED 1)
  (define WL_OUTPUT_SUBPIXEL_UNKNOWN 0)
  (define WL_OUTPUT_SUBPIXEL_NONE 1)
  (define WL_OUTPUT_SUBPIXEL_HORIZONTAL_RGB 2)
  (define WL_OUTPUT_SUBPIXEL_HORIZONTAL_BGR 3)
  (define WL_OUTPUT_SUBPIXEL_VERTICAL_RGB 4)
  (define WL_OUTPUT_SUBPIXEL_VERTICAL_BGR 5)
  (define WL_OUTPUT_TRANSFORM_NORMAL 0)
  (define WL_OUTPUT_TRANSFORM_90 1)
  (define WL_OUTPUT_TRANSFORM_180 2)
  (define WL_OUTPUT_TRANSFORM_270 3)
  (define WL_OUTPUT_TRANSFORM_FLIPPED 4)
  (define WL_OUTPUT_TRANSFORM_FLIPPED_90 5)
  (define WL_OUTPUT_TRANSFORM_FLIPPED_180 6)
  (define WL_OUTPUT_TRANSFORM_FLIPPED_270 7)
  (define WL_OUTPUT_MODE_CURRENT 1)
  (define WL_OUTPUT_MODE_PREFERRED 2)
  (define WL_SUBCOMPOSITOR_ERROR_BAD_SURFACE 0)
  (define WL_SUBCOMPOSITOR_ERROR_BAD_PARENT 1)
  (define WL_SUBSURFACE_ERROR_BAD_SURFACE 0)
  (define XDG_WM_BASE_ERROR_ROLE 0)
  (define XDG_WM_BASE_ERROR_DEFUNCT_SURFACES 1)
  (define XDG_WM_BASE_ERROR_NOT_THE_TOPMOST_POPUP 2)
  (define XDG_WM_BASE_ERROR_INVALID_POPUP_PARENT 3)
  (define XDG_WM_BASE_ERROR_INVALID_SURFACE_STATE 4)
  (define XDG_WM_BASE_ERROR_INVALID_POSITIONER 5)
  (define XDG_WM_BASE_ERROR_UNRESPONSIVE 6)
  (define XDG_POSITIONER_ERROR_INVALID_INPUT 0)
  (define XDG_POSITIONER_ANCHOR_NONE 0)
  (define XDG_POSITIONER_ANCHOR_TOP 1)
  (define XDG_POSITIONER_ANCHOR_BOTTOM 2)
  (define XDG_POSITIONER_ANCHOR_LEFT 3)
  (define XDG_POSITIONER_ANCHOR_RIGHT 4)
  (define XDG_POSITIONER_ANCHOR_TOP_LEFT 5)
  (define XDG_POSITIONER_ANCHOR_BOTTOM_LEFT 6)
  (define XDG_POSITIONER_ANCHOR_TOP_RIGHT 7)
  (define XDG_POSITIONER_ANCHOR_BOTTOM_RIGHT 8)
  (define XDG_POSITIONER_GRAVITY_NONE 0)
  (define XDG_POSITIONER_GRAVITY_TOP 1)
  (define XDG_POSITIONER_GRAVITY_BOTTOM 2)
  (define XDG_POSITIONER_GRAVITY_LEFT 3)
  (define XDG_POSITIONER_GRAVITY_RIGHT 4)
  (define XDG_POSITIONER_GRAVITY_TOP_LEFT 5)
  (define XDG_POSITIONER_GRAVITY_BOTTOM_LEFT 6)
  (define XDG_POSITIONER_GRAVITY_TOP_RIGHT 7)
  (define XDG_POSITIONER_GRAVITY_BOTTOM_RIGHT 8)
  (define XDG_POSITIONER_CONSTRAINT_ADJUSTMENT_NONE 0)
  (define XDG_POSITIONER_CONSTRAINT_ADJUSTMENT_SLIDE_X 1)
  (define XDG_POSITIONER_CONSTRAINT_ADJUSTMENT_SLIDE_Y 2)
  (define XDG_POSITIONER_CONSTRAINT_ADJUSTMENT_FLIP_X 4)
  (define XDG_POSITIONER_CONSTRAINT_ADJUSTMENT_FLIP_Y 8)
  (define XDG_POSITIONER_CONSTRAINT_ADJUSTMENT_RESIZE_X 16)
  (define XDG_POSITIONER_CONSTRAINT_ADJUSTMENT_RESIZE_Y 32)
  (define XDG_SURFACE_ERROR_NOT_CONSTRUCTED 1)
  (define XDG_SURFACE_ERROR_ALREADY_CONSTRUCTED 2)
  (define XDG_SURFACE_ERROR_UNCONFIGURED_BUFFER 3)
  (define XDG_SURFACE_ERROR_INVALID_SERIAL 4)
  (define XDG_SURFACE_ERROR_INVALID_SIZE 5)
  (define XDG_SURFACE_ERROR_DEFUNCT_ROLE_OBJECT 6)
  (define XDG_TOPLEVEL_ERROR_INVALID_RESIZE_EDGE 0)
  (define XDG_TOPLEVEL_ERROR_INVALID_PARENT 1)
  (define XDG_TOPLEVEL_ERROR_INVALID_SIZE 2)
  (define XDG_TOPLEVEL_RESIZE_EDGE_NONE 0)
  (define XDG_TOPLEVEL_RESIZE_EDGE_TOP 1)
  (define XDG_TOPLEVEL_RESIZE_EDGE_BOTTOM 2)
  (define XDG_TOPLEVEL_RESIZE_EDGE_LEFT 4)
  (define XDG_TOPLEVEL_RESIZE_EDGE_TOP_LEFT 5)
  (define XDG_TOPLEVEL_RESIZE_EDGE_BOTTOM_LEFT 6)
  (define XDG_TOPLEVEL_RESIZE_EDGE_RIGHT 8)
  (define XDG_TOPLEVEL_RESIZE_EDGE_TOP_RIGHT 9)
  (define XDG_TOPLEVEL_RESIZE_EDGE_BOTTOM_RIGHT 10)
  (define XDG_TOPLEVEL_STATE_MAXIMIZED 1)
  (define XDG_TOPLEVEL_STATE_FULLSCREEN 2)
  (define XDG_TOPLEVEL_STATE_RESIZING 3)
  (define XDG_TOPLEVEL_STATE_ACTIVATED 4)
  (define XDG_TOPLEVEL_STATE_TILED_LEFT 5)
  (define XDG_TOPLEVEL_STATE_TILED_RIGHT 6)
  (define XDG_TOPLEVEL_STATE_TILED_TOP 7)
  (define XDG_TOPLEVEL_STATE_TILED_BOTTOM 8)
  (define XDG_TOPLEVEL_STATE_SUSPENDED 9)
  (define XDG_TOPLEVEL_STATE_CONSTRAINED_LEFT 10)
  (define XDG_TOPLEVEL_STATE_CONSTRAINED_RIGHT 11)
  (define XDG_TOPLEVEL_STATE_CONSTRAINED_TOP 12)
  (define XDG_TOPLEVEL_STATE_CONSTRAINED_BOTTOM 13)
  (define XDG_TOPLEVEL_WM_CAPABILITIES_WINDOW_MENU 1)
  (define XDG_TOPLEVEL_WM_CAPABILITIES_MAXIMIZE 2)
  (define XDG_TOPLEVEL_WM_CAPABILITIES_FULLSCREEN 3)
  (define XDG_TOPLEVEL_WM_CAPABILITIES_MINIMIZE 4)
  (define XDG_POPUP_ERROR_INVALID_GRAB 0)
  (define ZXDG_TOPLEVEL_DECORATION_V1_ERROR_UNCONFIGURED_BUFFER
    0)
  (define ZXDG_TOPLEVEL_DECORATION_V1_ERROR_ALREADY_CONSTRUCTED
    1)
  (define ZXDG_TOPLEVEL_DECORATION_V1_ERROR_ORPHANED 2)
  (define ZXDG_TOPLEVEL_DECORATION_V1_ERROR_INVALID_MODE 3)
  (define ZXDG_TOPLEVEL_DECORATION_V1_MODE_CLIENT_SIDE 1)
  (define ZXDG_TOPLEVEL_DECORATION_V1_MODE_SERVER_SIDE 2)
  (define WP_CURSOR_SHAPE_DEVICE_V1_SHAPE_DEFAULT 1)
  (define WP_CURSOR_SHAPE_DEVICE_V1_SHAPE_CONTEXT_MENU 2)
  (define WP_CURSOR_SHAPE_DEVICE_V1_SHAPE_HELP 3)
  (define WP_CURSOR_SHAPE_DEVICE_V1_SHAPE_POINTER 4)
  (define WP_CURSOR_SHAPE_DEVICE_V1_SHAPE_PROGRESS 5)
  (define WP_CURSOR_SHAPE_DEVICE_V1_SHAPE_WAIT 6)
  (define WP_CURSOR_SHAPE_DEVICE_V1_SHAPE_CELL 7)
  (define WP_CURSOR_SHAPE_DEVICE_V1_SHAPE_CROSSHAIR 8)
  (define WP_CURSOR_SHAPE_DEVICE_V1_SHAPE_TEXT 9)
  (define WP_CURSOR_SHAPE_DEVICE_V1_SHAPE_VERTICAL_TEXT 10)
  (define WP_CURSOR_SHAPE_DEVICE_V1_SHAPE_ALIAS 11)
  (define WP_CURSOR_SHAPE_DEVICE_V1_SHAPE_COPY 12)
  (define WP_CURSOR_SHAPE_DEVICE_V1_SHAPE_MOVE 13)
  (define WP_CURSOR_SHAPE_DEVICE_V1_SHAPE_NO_DROP 14)
  (define WP_CURSOR_SHAPE_DEVICE_V1_SHAPE_NOT_ALLOWED 15)
  (define WP_CURSOR_SHAPE_DEVICE_V1_SHAPE_GRAB 16)
  (define WP_CURSOR_SHAPE_DEVICE_V1_SHAPE_GRABBING 17)
  (define WP_CURSOR_SHAPE_DEVICE_V1_SHAPE_E_RESIZE 18)
  (define WP_CURSOR_SHAPE_DEVICE_V1_SHAPE_N_RESIZE 19)
  (define WP_CURSOR_SHAPE_DEVICE_V1_SHAPE_NE_RESIZE 20)
  (define WP_CURSOR_SHAPE_DEVICE_V1_SHAPE_NW_RESIZE 21)
  (define WP_CURSOR_SHAPE_DEVICE_V1_SHAPE_S_RESIZE 22)
  (define WP_CURSOR_SHAPE_DEVICE_V1_SHAPE_SE_RESIZE 23)
  (define WP_CURSOR_SHAPE_DEVICE_V1_SHAPE_SW_RESIZE 24)
  (define WP_CURSOR_SHAPE_DEVICE_V1_SHAPE_W_RESIZE 25)
  (define WP_CURSOR_SHAPE_DEVICE_V1_SHAPE_EW_RESIZE 26)
  (define WP_CURSOR_SHAPE_DEVICE_V1_SHAPE_NS_RESIZE 27)
  (define WP_CURSOR_SHAPE_DEVICE_V1_SHAPE_NESW_RESIZE 28)
  (define WP_CURSOR_SHAPE_DEVICE_V1_SHAPE_NWSE_RESIZE 29)
  (define WP_CURSOR_SHAPE_DEVICE_V1_SHAPE_COL_RESIZE 30)
  (define WP_CURSOR_SHAPE_DEVICE_V1_SHAPE_ROW_RESIZE 31)
  (define WP_CURSOR_SHAPE_DEVICE_V1_SHAPE_ALL_SCROLL 32)
  (define WP_CURSOR_SHAPE_DEVICE_V1_SHAPE_ZOOM_IN 33)
  (define WP_CURSOR_SHAPE_DEVICE_V1_SHAPE_ZOOM_OUT 34)
  (define WP_CURSOR_SHAPE_DEVICE_V1_SHAPE_DND_ASK 35)
  (define WP_CURSOR_SHAPE_DEVICE_V1_SHAPE_ALL_RESIZE 36)
  (define WP_CURSOR_SHAPE_DEVICE_V1_ERROR_INVALID_SHAPE 1))
