;;; c2ffi-gen.ss -- turn c2ffi JSON output into a Chez Scheme FFI library.
;;;
;;; Usage:
;;;   scheme --libdirs tools --script tools/c2ffi-gen.ss macros SPEC MACROS.h HEADER OUT.h
;;;       Filter the macro file produced by `c2ffi -M` down to the macros named
;;;       in SPEC, producing a header that a second c2ffi pass can evaluate.
;;;   scheme --libdirs tools --script tools/c2ffi-gen.ss library SPEC DECLS.json CONSTS.json OUT.ss [SO=PATH ...]
;;;       Generate the Scheme library from the declarations and constants.
;;;   scheme --libdirs tools --script tools/c2ffi-gen.ss relink LIB.ss OUT.ss [SO=PATH ...]
;;;       Rewrite the shared objects loaded by an already generated library,
;;;       without c2ffi.  The result is identical to generating the library
;;;       with the same SO=PATH arguments.
;;;
;;; SO=PATH replaces the shared object SO listed in the spec (e.g.
;;; libwayland-client.so.0) by PATH, typically an absolute path for systems
;;; where libraries are not found by soname (Nix).

(import (chezscheme) (json))

;;; ------------------------------------------------------------------
;;; Spec handling

(define (read-spec path)
  (call-with-input-file path
    (lambda (p)
      (let loop ([acc '()])
        (let ([x (read p)])
          (if (eof-object? x) (reverse acc) (loop (cons x acc))))))))

(define (spec-ref spec key)
  (let ([e (assq key spec)])
    (if e (cdr e) '())))

;;; ------------------------------------------------------------------
;;; Pass 1: macro filtering

(define (string-prefix? pre s)
  (and (<= (string-length pre) (string-length s))
       (string=? pre (substring s 0 (string-length pre)))))

(define (macro-line-name line)
  ;; lines look like: const long __c2ffi_NAME = NAME;
  (let ([i (let loop ([i 0])
             (cond [(> (+ i 7) (string-length line)) #f]
                   [(string=? (substring line i (+ i 7)) "__c2ffi") i]
                   [else (loop (+ i 1))]))])
    (and i
         (let* ([start (+ i 8)]
                [end (let loop ([j start])
                       (if (or (= j (string-length line))
                               (char=? (string-ref line j) #\space))
                           j
                           (loop (+ j 1))))])
           (substring line start end)))))

(define (gen-macros spec-path macros-path header out-path)
  (let* ([spec (read-spec spec-path)]
         [wanted (map symbol->string (spec-ref spec 'macros))]
         [lines (call-with-input-file macros-path
                  (lambda (p)
                    (let loop ([acc '()])
                      (let ([l (get-line p)])
                        (if (eof-object? l) (reverse acc) (loop (cons l acc)))))))])
    (call-with-output-file out-path
      (lambda (o)
        (fprintf o "/* generated by tools/c2ffi-gen.ss -- do not edit */~%")
        (fprintf o "#include ~s~%" header)
        (for-each
         (lambda (l)
           (let ([n (macro-line-name l)])
             (when (and n (member n wanted))
               (fprintf o "~a~%" l))))
         lines))
      'replace)
    (for-each
     (lambda (w)
       (unless (exists (lambda (l) (equal? (macro-line-name l) w)) lines)
         (errorf 'c2ffi-gen "macro ~a not found" w)))
     wanted)))

;;; ------------------------------------------------------------------
;;; Pass 2: library generation

(define typedefs (make-hashtable string-hash string=?))   ; name -> type
(define structs (make-hashtable string-hash string=?))    ; name -> decl (with fields)
(define unions (make-hashtable string-hash string=?))
(define anon-structs (make-hashtable equal-hash equal?))  ; id -> decl
(define functions (make-hashtable string-hash string=?))
(define enums '())                                        ; list of (name . value)

(define (index-decls! decls)
  (for-each
   (lambda (d)
     (let ([tag (jref d "tag")] [name (jref d "name")])
       (cond
         [(equal? tag "typedef") (hashtable-set! typedefs name (jref d "type"))]
         [(member tag '("struct" "union"))
          (let ([table (if (equal? tag "struct") structs unions)])
            (cond
              [(equal? name "")
               (hashtable-set! anon-structs (cons tag (jref d "id")) d)]
              ;; keep the complete definition, not forward declarations
              [(or (pair? (jref d "fields"))
                   (not (hashtable-contains? table name)))
               (hashtable-set! table name d)]))]
         [(equal? tag "function") (hashtable-set! functions name d)]
         [(equal? tag "enum")
          (for-each (lambda (f) (set! enums (cons (cons (jref f "name") (jref f "value")) enums)))
                    (jref d "fields"))])))
   decls)
  ;; give anonymous structs typedef'd names their typedef name
  (let-values ([(names types) (hashtable-entries typedefs)])
    (vector-for-each
     (lambda (n t)
       (let ([tag (jref t "tag")])
         (when (and (member tag '(":struct" ":union")) (equal? (jref t "name") ""))
           (let ([d (hashtable-ref anon-structs
                                   (cons (if (equal? tag ":struct") "struct" "union") (jref t "id"))
                                   #f)])
             (when d
               (hashtable-set! (if (equal? tag ":struct") structs unions) n d)
               (hashtable-set! typedefs n `(("tag" . ,tag) ("name" . ,n) ("id" . 0))))))))
     names types)))

(define primitive-types
  '((":int" . int) (":unsigned-int" . unsigned-int)
    (":char" . integer-8) (":signed-char" . integer-8) (":unsigned-char" . unsigned-8)
    (":short" . short) (":unsigned-short" . unsigned-short)
    (":long" . long) (":unsigned-long" . unsigned-long)
    (":long-long" . integer-64) (":unsigned-long-long" . unsigned-64)
    (":float" . float) (":double" . double) (":_Bool" . unsigned-8)
    (":enum" . int) (":function-pointer" . uptr)))

;; follow typedef chains until reaching a structural type
(define (resolve t)
  (let ([tag (jref t "tag")])
    (cond
      [(assoc tag primitive-types) t]
      [(member tag '(":pointer" ":array" ":struct" ":union" "struct" "union" ":void" ":bitfield")) t]
      [(hashtable-ref typedefs tag #f) => resolve]
      [else (errorf 'c2ffi-gen "unknown type ~s" tag)])))

(define (struct-decl-of t)
  ;; t is a resolved struct/union type (reference or inline)
  (let* ([tag (jref t "tag")]
         [kind (if (member tag '(":struct" "struct")) "struct" "union")]
         [name (jref t "name")])
    (cond
      [(pair? (jref t "fields")) t]
      [(equal? name "")
       (hashtable-ref anon-structs (cons kind (jref t "id")) #f)]
      [else (hashtable-ref (if (equal? kind "struct") structs unions) name #f)])))

(define (struct-complete? d) (and d (pair? (jref d "fields"))))

;;; ftype generation -------------------------------------------------

(define emitted-ftypes '())   ; names (strings) of structs to emit, in order
(define pending (make-hashtable string-hash string=?))

(define (request-ftype! name)
  (unless (hashtable-contains? pending name)
    (hashtable-set! pending name #t)
    (let ([d (or (hashtable-ref structs name #f) (hashtable-ref unions name #f))])
      (when (struct-complete? d)
        (for-each (lambda (f) (walk-type (jref f "type"))) (jref d "fields"))
        (set! emitted-ftypes (cons name emitted-ftypes))))))

(define (walk-type t)
  (let* ([r (resolve t)] [tag (jref r "tag")])
    (cond
      [(member tag '(":pointer" ":array")) (walk-type (jref r "type"))]
      [(member tag '(":bitfield")) (void)]
      [(member tag '(":struct" ":union" "struct" "union"))
       (let ([d (struct-decl-of r)])
         (cond
           [(not (struct-complete? d)) (void)]
           [(equal? (jref d "name") "")
            (for-each (lambda (f) (walk-type (jref f "type"))) (jref d "fields"))]
           [else (request-ftype! (jref d "name"))]))]
      [else (void)])))

(define (ftype-name-of d) (string->symbol (jref d "name")))

(define (ftype-of t)
  (let* ([r (resolve t)] [tag (jref r "tag")])
    (cond
      [(assoc tag primitive-types) => cdr]
      [(equal? tag ":void") 'unsigned-8]
      [(equal? tag ":pointer")
       (let* ([to (resolve (jref r "type"))] [tt (jref to "tag")])
         (if (member tt '(":struct" ":union" "struct" "union"))
             (let ([d (struct-decl-of to)])
               (if (and (struct-complete? d) (not (equal? (jref d "name") ""))
                        (member (jref d "name") emitted-ftypes))
                   `(* ,(ftype-name-of d))
                   'void*))
             'void*))]
      [(equal? tag ":array")
       `(array ,(jref r "size") ,(ftype-of (jref r "type")))]
      [(member tag '(":struct" ":union" "struct" "union"))
       (let ([d (struct-decl-of r)])
         (cond
           [(not (struct-complete? d)) (errorf 'c2ffi-gen "incomplete struct by value ~s" r)]
           [(equal? (jref d "name") "") (struct-body d)]
           [else (ftype-name-of d)]))]
      [else (errorf 'c2ffi-gen "cannot map type ~s" r)])))

(define (field-name f i)
  (let ([n (jref f "name")])
    (if (equal? n "") (string->symbol (format "_anon~a" i)) (string->symbol n))))

(define (struct-body d)
  (let ([kind (if (member (jref d "tag") '("struct" ":struct")) 'struct 'union)])
    (let loop ([fs (jref d "fields")] [i 0] [acc '()])
      (cond
        [(null? fs) `(,kind ,@(reverse acc))]
        [(equal? (jref* (car fs) "type" "tag") ":bitfield")
         ;; group consecutive bitfields into one storage unit
         (let* ([unit-bits (jref* (car fs) "type" "type" "bit-size")]
                [unit-bits (if (number? unit-bits) unit-bits 32)]
                [start (jref (car fs) "bit-offset")])
           (let gather ([fs fs] [bits '()] [used 0] [i i])
             (if (and (pair? fs)
                      (equal? (jref* (car fs) "type" "tag") ":bitfield")
                      (<= (+ used (jref* (car fs) "type" "width")) unit-bits))
                 (let ([w (jref* (car fs) "type" "width")])
                   (gather (cdr fs) (cons `(,(field-name (car fs) i) unsigned ,w) bits) (+ used w) (+ i 1)))
                 (let ([bits (if (< used unit-bits)
                                 (cons `(,(string->symbol (format "_pad~a" i)) unsigned ,(- unit-bits used)) bits)
                                 bits)])
                   (loop fs (+ i 1)
                         (cons `(,(string->symbol (format "_bits~a" start)) (bits ,@(reverse bits))) acc))))))]
        [else
         (loop (cdr fs) (+ i 1)
               (cons `(,(field-name (car fs) i) ,(ftype-of (jref (car fs) "type"))) acc))]))))

;;; foreign-procedure generation --------------------------------------

;; C names that clash with (chezscheme) exports (read, write, getenv, ...)
;; are bound with a c- prefix.
(define chez-env (environment '(chezscheme)))
(define (scheme-name str)
  (let ([s (string->symbol str)])
    (if (top-level-bound? s chez-env)
        (string->symbol (string-append "c-" str))
        s)))

;; c2ffi evaluates integer macros but leaves string macros without a value;
;; recover those from the #define line at the recorded source location.
(define (const-value c)
  (let ([v (jref c "value" 'none)])
    (if (not (eq? v 'none))
        v
        (let* ([loc (jref c "location")]
               [parts (let split ([s loc] [acc '()])
                        (let ([i (let find ([i 0])
                                   (cond [(= i (string-length s)) #f]
                                         [(char=? (string-ref s i) #\:) i]
                                         [else (find (+ i 1))]))])
                          (if i
                              (split (substring s (+ i 1) (string-length s))
                                     (cons (substring s 0 i) acc))
                              (reverse (cons s acc)))))]
               [file (car parts)]
               [line (string->number (cadr parts))]
               [text (call-with-input-file file
                       (lambda (p)
                         (let loop ([n 1])
                           (let ([l (get-line p)])
                             (if (= n line) l (loop (+ n 1)))))))]
               [q (let find ([i 0])
                    (cond [(= i (string-length text))
                           (errorf 'c2ffi-gen "no value for constant ~a" (jref c "name"))]
                          [(char=? (string-ref text i) #\") i]
                          [else (find (+ i 1))]))])
          (read (open-input-string (substring text q (string-length text))))))))

(define (proc-type t param?)
  (let* ([r (resolve t)] [tag (jref r "tag")])
    (cond
      [(equal? tag ":void") 'void]
      [(equal? tag ":pointer")
       (let ([to (resolve (jref r "type"))])
         (if (and param? (equal? (jref to "tag") ":char")) 'utf-8 'uptr))]
      [(equal? tag ":array") 'uptr]
      [(assoc tag primitive-types) => cdr]
      [else (errorf 'c2ffi-gen "cannot pass by value ~s" r)])))

(define (gen-function entry)
  (let* ([name (if (pair? entry) (car entry) entry)]
         [overrides (if (pair? entry) (cdr entry) '())]
         [d (or (hashtable-ref functions (symbol->string name) #f)
                (errorf 'c2ffi-gen "function ~a not found" name))])
    ;; Variadic functions get fixed extra arguments from a (&rest type ...)
    ;; override; on x86-64 SysV this is ABI-compatible for integer arguments.
    (when (and (jref d "variadic") (not (assq '&rest overrides)))
      (errorf 'c2ffi-gen "~a is variadic; give (&rest type ...) in the spec" name))
    (let ([params
           (append
            (map (lambda (p)
                   (let ([o (assq (string->symbol (jref p "name")) overrides)])
                     (if o (cadr o) (proc-type (jref p "type") #t))))
                 (jref d "parameters"))
            (let ([r (assq '&rest overrides)]) (if r (cdr r) '())))])
      `(define ,(scheme-name (symbol->string name))
         (foreign-procedure ,(symbol->string name) ,params
                            ,(proc-type (jref d "return-type") #f))))))

(define (parse-overrides args)
  (map (lambda (a)
         (let loop ([i 0])
           (cond
             [(= i (string-length a)) (errorf 'c2ffi-gen "expected SO=PATH, got ~s" a)]
             [(char=? (string-ref a i) #\=)
              (cons (substring a 0 i) (substring a (+ i 1) (string-length a)))]
             [else (loop (+ i 1))])))
       args))

(define (apply-overrides sos overrides)
  (for-each
   (lambda (o)
     (unless (member (car o) sos)
       (errorf 'c2ffi-gen "~a is not one of the shared objects ~s" (car o) sos)))
   overrides)
  (map (lambda (so) (cond [(assoc so overrides) => cdr] [else so])) sos))

(define (write-library lib out-path)
  (call-with-output-file out-path
    (lambda (o)
      (fprintf o ";;; Generated by tools/c2ffi-gen.ss from c2ffi output of ffi/bindings.h.~%")
      (fprintf o ";;; Do not edit; run `make bindings` to regenerate.~%~%")
      (parameterize ([print-radix 10])
        (pretty-print lib o)))
    'replace))

;; LIB is (library NAME (export ...) (import ...) (define shared-objects-loaded
;; (begin (load-shared-object SO) ... #t)) ...), as written by gen-library.
(define (relink lib-path out-path overrides)
  (let ([lib (call-with-input-file lib-path read)])
    (define (loader? d)
      (and (pair? d) (eq? (car d) 'define) (eq? (cadr d) 'shared-objects-loaded)))
    (let ([sos (map cadr (let ([body (caddr (find loader? lib))])
                           (filter pair? (cdr body))))])
      (write-library
       (map (lambda (d)
              (if (loader? d)
                  (loader-definition (apply-overrides sos overrides))
                  d))
            lib)
       out-path))))

(define (loader-definition sos)
  `(define shared-objects-loaded
     (begin
       ,@(map (lambda (so) `(load-shared-object ,so)) sos)
       #t)))

(define (gen-library spec-path decls-path consts-path out-path overrides)
  (let* ([spec (read-spec spec-path)]
         [decls (json-read-file decls-path)]
         ;; c2ffi emits macros in hash order; sort for reproducible output
         [consts (list-sort (lambda (a b) (string<? (jref a "name") (jref b "name")))
                            (filter (lambda (d) (equal? (jref d "tag") "const"))
                                    (json-read-file consts-path)))])
    (index-decls! decls)
    (for-each (lambda (s) (request-ftype! (symbol->string s)))
              (append (spec-ref spec 'structs) (spec-ref spec 'unions)))
    (set! emitted-ftypes (reverse emitted-ftypes))
    (let* ([ftype-defs
            (map (lambda (n)
                   (let ([d (or (hashtable-ref structs n #f) (hashtable-ref unions n #f))])
                     (list (string->symbol n) (struct-body d))))
                 emitted-ftypes)]
           [fn-defs (map gen-function (spec-ref spec 'functions))]
           [prefixes (spec-ref spec 'enum-prefixes)]
           [enum-defs
            (let loop ([es (reverse enums)] [seen '()] [acc '()])
              (cond
                [(null? es) (reverse acc)]
                [(and (exists (lambda (p) (string-prefix? p (caar es))) prefixes)
                      (not (member (caar es) seen)))
                 (loop (cdr es) (cons (caar es) seen)
                       (cons `(define ,(string->symbol (caar es)) ,(cdar es)) acc))]
                [else (loop (cdr es) seen acc)]))]
           [const-defs
            (map (lambda (c)
                   `(define ,(scheme-name (jref c "name")) ,(const-value c)))
                 consts)]
           [exports (append (map car ftype-defs) (map cadr fn-defs)
                            (map cadr enum-defs) (map cadr const-defs))])
      (write-library
       `(library ,(car (spec-ref spec 'library-name))
          (export ,@exports)
          (import (chezscheme))
          ,(loader-definition (apply-overrides (spec-ref spec 'shared-objects) overrides))
          ,@(if (null? ftype-defs) '() `((define-ftype ,@ftype-defs)))
          ,@fn-defs
          ,@enum-defs
          ,@const-defs)
       out-path))))

(let ([args (command-line-arguments)])
  (cond
    [(and (= (length args) 5) (equal? (car args) "macros"))
     (apply gen-macros (cdr args))]
    [(and (>= (length args) 5) (equal? (car args) "library"))
     (apply gen-library (append (list-head (cdr args) 4)
                                (list (parse-overrides (list-tail args 5)))))]
    [(and (>= (length args) 3) (equal? (car args) "relink"))
     (relink (cadr args) (caddr args) (parse-overrides (list-tail args 3)))]
    [else
     (display "usage: c2ffi-gen.ss macros SPEC MACROS.h HEADER OUT.h\n       c2ffi-gen.ss library SPEC DECLS.json CONSTS.json OUT.ss [SO=PATH ...]\n       c2ffi-gen.ss relink LIB.ss OUT.ss [SO=PATH ...]\n")
     (exit 1)]))
